server: 
    port: 8090
    tomcat:
        access_log_enabled: false
        basedir: target/tomcat
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    enabled: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka   

logging:
   file: ${spring.application.name}.log
   path: /var/log
   level:
      root: INFO
      org: 
          springframework: 
                    web: INFO
   
   
serenity:
  security:
    audience: SARASERENITY
    keyprovider:
      publicKeys:
        -
          alias: sts_SHA1withRSA
          encodedKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjAUCdrKSsrwkfzcqsiBhecKuTOriACZ0GkTh0OGY59bcYyox6nPCE2q9YBAEWtZkc9sDsy1BJq8PU748GOjSptUsWIYDy02Yzl8+rDsCp+wYSwixunE5sfL9wyHJE1qq79j7K3FcJiqsQUVdvZbB2oeDaS7s35JjiWCQUWkxMGuuuqGncXbFVfOOalpbL+QoT9Br9mbpsy6sQn17IVQA1M+YRzo1hEOauPGdPa1VwTcNz8cJ/CMzIJMK41Woi0q7VlguYTzO+cbLf+UQOW/L4D1TI2ipeLOMhuYgBsKOwXifiQnVDGVXEKoIaFqRvA71uGecdalnynaP4WoeTFvcZwIDAQAB           

security:
  ignored: /public/**, /swagger-ui.html, /webjars/**, /swagger-resources/**, /v2/api-docs/**, /configuration/ui/**, /configuration/security/**, /health, /static/**
  basic:
    enable: true

spring: 
  application:
    name: ofertaguiada        
            
app:
  security:
    # NO_SECURED | SECURED_BY_TOKEN
    type: NO_SECURED
    # When type = NO_SECURED prefix = /public
    # When type = SECURED_BY_TOKEN prefix = (empty)
    prefix: /public
    # Authorization | GS-AUTH-TOKEN    
    header: Authorization
    mock:
      user: XXTEST        
    domain: 
  crossorigin: 
    generatepdf: "*"
    analyzefile: "*"
