package com.isb.og.common.component;

import java.lang.reflect.Field;

/**
 * Handler interface to support values that could not be generated by the
 * populator..
 * 
 * @author Vector ITC Group
 */
public interface MockCantGenerateValueHandler {
    
    /**
     * Handles the field that can not be generated.
     * 
     * @param fieldType {@link Class}
     * @return {@link Object}
     */
    Object handle(
        Class<?> fieldType);
        
    /**
     * Sets the field.
     * 
     * @param field {@link Field}
     */
    void setField(
        Field field);
}
