//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 10:30:19 AM CEST 
//


package com.isb.og.security.wsdl.facseg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Timestamp1" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="Timestamp2" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type", propOrder = {
    "timestamp1",
    "timestamp2"
})
public class ComIsbAlFacsegSecurityCbCBSearchTimestampsType {

    @XmlElement(name = "Timestamp1")
    protected XMLGregorianCalendar timestamp1;
    @XmlElement(name = "Timestamp2")
    protected XMLGregorianCalendar timestamp2;

    /**
     * Gets the value of the timestamp1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp1() {
        return timestamp1;
    }

    /**
     * Sets the value of the timestamp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp1(XMLGregorianCalendar value) {
        this.timestamp1 = value;
    }

    /**
     * Gets the value of the timestamp2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp2() {
        return timestamp2;
    }

    /**
     * Sets the value of the timestamp2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp2(XMLGregorianCalendar value) {
        this.timestamp2 = value;
    }

}
