//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:13:32 PM CEST 
//


package com.isb.og.security.wsdl.facseg;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.al.facseg.security.cb.CB_UserMobileDevice_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.al.facseg.security.cb.CB_UserMobileDevice_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deviceID" type="{http://www.isban.es/webservices/TDCs}MOBILE_DEVICE_ID_Type" minOccurs="0"/>
 *         &lt;element name="aliasDevice" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" minOccurs="0"/>
 *         &lt;element name="isActiveDevice" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="mobileso" type="{http://www.isban.es/webservices/TDCs}CODIGO_NUMERICO_1_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.al.facseg.security.cb.CB_UserMobileDevice_Type", propOrder = {
    "deviceID",
    "aliasDevice",
    "isActiveDevice",
    "mobileso"
})
public class ComIsbAlFacsegSecurityCbCBUserMobileDeviceType {

    protected String deviceID;
    protected String aliasDevice;
    protected String isActiveDevice;
    protected Integer mobileso;

    /**
     * Gets the value of the deviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceID(String value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the aliasDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAliasDevice() {
        return aliasDevice;
    }

    /**
     * Sets the value of the aliasDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAliasDevice(String value) {
        this.aliasDevice = value;
    }

    /**
     * Gets the value of the isActiveDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsActiveDevice() {
        return isActiveDevice;
    }

    /**
     * Sets the value of the isActiveDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsActiveDevice(String value) {
        this.isActiveDevice = value;
    }

    /**
     * Gets the value of the mobileso property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMobileso() {
        return mobileso;
    }

    /**
     * Sets the value of the mobileso property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMobileso(Integer value) {
        this.mobileso = value;
    }

}
