//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:13:32 PM CEST 
//


package com.isb.og.security.wsdl.facseg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for com.isb.al.facseg.security.cb.CB_User_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.al.facseg.security.cb.CB_User_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attSurname" type="{http://www.isban.es/webservices/TDCs}APELLIDO_Type" minOccurs="0"/>
 *         &lt;element name="attFullName" type="{http://www.isban.es/webservices/TDCs}NOMBRE_DE_PERSONA_Type" minOccurs="0"/>
 *         &lt;element name="attUID" type="{http://www.isban.es/webservices/TDCs}UID_Type" minOccurs="0"/>
 *         &lt;element name="attAlias" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" minOccurs="0"/>
 *         &lt;element name="attPassword" type="{http://www.isban.es/webservices/TDCs}PASSWORD_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="attSignKey" type="{http://www.isban.es/webservices/TDCs}PASSWORD_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="attLastLogonDate" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attLastChangePWDate" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attEntity" type="{http://www.isban.es/webservices/TDCs}EMPRESA_Type" minOccurs="0"/>
 *         &lt;element name="attEnvironment" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" minOccurs="0"/>
 *         &lt;element name="attExpirationDate" type="{http://www.isban.es/webservices/TDCs}FECHA_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="attFirstTimeSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attFirstTime" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attRevokedPassword" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attRevokedSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attMobile" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attMobile" type="{http://www.isban.es/webservices/TDCs}TELEFONO_INTERNACIONAL_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attCreditCardNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attCreditCardNumber" type="{http://www.isban.es/webservices/TDCs}PAN_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attContractNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attContractNumber" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attPersonNumber" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" minOccurs="0"/>
 *         &lt;element name="attBeforeLastLogonDate" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attSignMethods" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_VerTypes_Type" minOccurs="0"/>
 *         &lt;element name="attPersonalID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attPersonalID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attName" type="{http://www.isban.es/webservices/TDCs}NOMBRE_DE_PERSONA_Type" minOccurs="0"/>
 *         &lt;element name="attDocument" type="{http://www.isban.es/webservices/TDCc}DOCUM_PERSONA_CORPORATIVO_Type" minOccurs="0"/>
 *         &lt;element name="attDocumentRep" type="{http://www.isban.es/webservices/TDCc}DOCUM_PERSONA_CORPORATIVO_Type" minOccurs="0"/>
 *         &lt;element name="attLanguage" type="{http://www.isban.es/webservices/TDCc}IDIOMA_CORPORATIVO_Type" minOccurs="0"/>
 *         &lt;element name="attLastUnsuccessLogon" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attSecondSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attLastSignDate" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attLogonImage" type="{http://www.isban.es/webservices/TDCs}URL_Type" minOccurs="0"/>
 *         &lt;element name="attLogonPhrase" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_MEDIA_Type" minOccurs="0"/>
 *         &lt;element name="attmTANRevokedSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attCompanyID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attCompanyID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attCompanyName" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_MEDIA_Type" minOccurs="0"/>
 *         &lt;element name="attLegalPersonNumber" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" minOccurs="0"/>
 *         &lt;element name="attStartDate" type="{http://www.isban.es/webservices/TDCs}FECHA_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="attEndDate" type="{http://www.isban.es/webservices/TDCs}FECHA_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="attLockUser" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attAuthenticationLastError" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attSignByPositionsActive" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attRevocationDate" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attLockDate" type="{http://www.isban.es/webservices/TDCs}TIMESTAMP_ALTA_Type" minOccurs="0"/>
 *         &lt;element name="attPasswordActive" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attOTPPushID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attOTPPushID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_LARGA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attOTPPushRevokedSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.al.facseg.security.cb.CB_User_Type", propOrder = {
    "attSurname",
    "attFullName",
    "attUID",
    "attAlias",
    "attPassword",
    "attSignKey",
    "attLastLogonDate",
    "attLastChangePWDate",
    "attEntity",
    "attEnvironment",
    "attExpirationDate",
    "attFirstTimeSign",
    "attFirstTime",
    "attRevokedPassword",
    "attRevokedSign",
    "attMobile",
    "attCreditCardNumber",
    "attContractNumber",
    "attPersonNumber",
    "attBeforeLastLogonDate",
    "attSignMethods",
    "attPersonalID",
    "attName",
    "attDocument",
    "attDocumentRep",
    "attLanguage",
    "attLastUnsuccessLogon",
    "attSecondSign",
    "attLastSignDate",
    "attLogonImage",
    "attLogonPhrase",
    "attmTANRevokedSign",
    "attCompanyID",
    "attCompanyName",
    "attLegalPersonNumber",
    "attStartDate",
    "attEndDate",
    "attLockUser",
    "attAuthenticationLastError",
    "attSignByPositionsActive",
    "attRevocationDate",
    "attLockDate",
    "attPasswordActive",
    "attOTPPushID",
    "attOTPPushRevokedSign"
})
public class ComIsbAlFacsegSecurityCbCBUserType {

    protected String attSurname;
    protected String attFullName;
    protected String attUID;
    protected String attAlias;
    protected String attPassword;
    protected String attSignKey;
    protected XMLGregorianCalendar attLastLogonDate;
    protected XMLGregorianCalendar attLastChangePWDate;
    protected String attEntity;
    protected String attEnvironment;
    protected XMLGregorianCalendar attExpirationDate;
    protected String attFirstTimeSign;
    protected String attFirstTime;
    protected String attRevokedPassword;
    protected String attRevokedSign;
    protected ComIsbAlFacsegSecurityCbCBUserType.AttMobile attMobile;
    protected ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber attCreditCardNumber;
    protected ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber attContractNumber;
    protected NUMPERSONACLIENTEType attPersonNumber;
    protected XMLGregorianCalendar attBeforeLastLogonDate;
    protected ComIsbAlFacsegSecurityCbCBVerTypesType attSignMethods;
    protected ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID attPersonalID;
    protected String attName;
    protected DOCUMPERSONACORPORATIVOType attDocument;
    protected DOCUMPERSONACORPORATIVOType attDocumentRep;
    protected IDIOMACORPORATIVOType attLanguage;
    protected XMLGregorianCalendar attLastUnsuccessLogon;
    protected String attSecondSign;
    protected XMLGregorianCalendar attLastSignDate;
    protected String attLogonImage;
    protected String attLogonPhrase;
    protected String attmTANRevokedSign;
    protected ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID attCompanyID;
    protected String attCompanyName;
    protected NUMPERSONACLIENTEType attLegalPersonNumber;
    protected XMLGregorianCalendar attStartDate;
    protected XMLGregorianCalendar attEndDate;
    protected String attLockUser;
    protected String attAuthenticationLastError;
    protected String attSignByPositionsActive;
    protected XMLGregorianCalendar attRevocationDate;
    protected XMLGregorianCalendar attLockDate;
    protected String attPasswordActive;
    protected ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID attOTPPushID;
    protected String attOTPPushRevokedSign;

    /**
     * Gets the value of the attSurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttSurname() {
        return attSurname;
    }

    /**
     * Sets the value of the attSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttSurname(String value) {
        this.attSurname = value;
    }

    /**
     * Gets the value of the attFullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttFullName() {
        return attFullName;
    }

    /**
     * Sets the value of the attFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttFullName(String value) {
        this.attFullName = value;
    }

    /**
     * Gets the value of the attUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttUID() {
        return attUID;
    }

    /**
     * Sets the value of the attUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttUID(String value) {
        this.attUID = value;
    }

    /**
     * Gets the value of the attAlias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttAlias() {
        return attAlias;
    }

    /**
     * Sets the value of the attAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttAlias(String value) {
        this.attAlias = value;
    }

    /**
     * Gets the value of the attPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttPassword() {
        return attPassword;
    }

    /**
     * Sets the value of the attPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttPassword(String value) {
        this.attPassword = value;
    }

    /**
     * Gets the value of the attSignKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttSignKey() {
        return attSignKey;
    }

    /**
     * Sets the value of the attSignKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttSignKey(String value) {
        this.attSignKey = value;
    }

    /**
     * Gets the value of the attLastLogonDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttLastLogonDate() {
        return attLastLogonDate;
    }

    /**
     * Sets the value of the attLastLogonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttLastLogonDate(XMLGregorianCalendar value) {
        this.attLastLogonDate = value;
    }

    /**
     * Gets the value of the attLastChangePWDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttLastChangePWDate() {
        return attLastChangePWDate;
    }

    /**
     * Sets the value of the attLastChangePWDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttLastChangePWDate(XMLGregorianCalendar value) {
        this.attLastChangePWDate = value;
    }

    /**
     * Gets the value of the attEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttEntity() {
        return attEntity;
    }

    /**
     * Sets the value of the attEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttEntity(String value) {
        this.attEntity = value;
    }

    /**
     * Gets the value of the attEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttEnvironment() {
        return attEnvironment;
    }

    /**
     * Sets the value of the attEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttEnvironment(String value) {
        this.attEnvironment = value;
    }

    /**
     * Gets the value of the attExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttExpirationDate() {
        return attExpirationDate;
    }

    /**
     * Sets the value of the attExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttExpirationDate(XMLGregorianCalendar value) {
        this.attExpirationDate = value;
    }

    /**
     * Gets the value of the attFirstTimeSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttFirstTimeSign() {
        return attFirstTimeSign;
    }

    /**
     * Sets the value of the attFirstTimeSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttFirstTimeSign(String value) {
        this.attFirstTimeSign = value;
    }

    /**
     * Gets the value of the attFirstTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttFirstTime() {
        return attFirstTime;
    }

    /**
     * Sets the value of the attFirstTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttFirstTime(String value) {
        this.attFirstTime = value;
    }

    /**
     * Gets the value of the attRevokedPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttRevokedPassword() {
        return attRevokedPassword;
    }

    /**
     * Sets the value of the attRevokedPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttRevokedPassword(String value) {
        this.attRevokedPassword = value;
    }

    /**
     * Gets the value of the attRevokedSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttRevokedSign() {
        return attRevokedSign;
    }

    /**
     * Sets the value of the attRevokedSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttRevokedSign(String value) {
        this.attRevokedSign = value;
    }

    /**
     * Gets the value of the attMobile property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttMobile }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttMobile getAttMobile() {
        return attMobile;
    }

    /**
     * Sets the value of the attMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttMobile }
     *     
     */
    public void setAttMobile(ComIsbAlFacsegSecurityCbCBUserType.AttMobile value) {
        this.attMobile = value;
    }

    /**
     * Gets the value of the attCreditCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber getAttCreditCardNumber() {
        return attCreditCardNumber;
    }

    /**
     * Sets the value of the attCreditCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber }
     *     
     */
    public void setAttCreditCardNumber(ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber value) {
        this.attCreditCardNumber = value;
    }

    /**
     * Gets the value of the attContractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber getAttContractNumber() {
        return attContractNumber;
    }

    /**
     * Sets the value of the attContractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber }
     *     
     */
    public void setAttContractNumber(ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber value) {
        this.attContractNumber = value;
    }

    /**
     * Gets the value of the attPersonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public NUMPERSONACLIENTEType getAttPersonNumber() {
        return attPersonNumber;
    }

    /**
     * Sets the value of the attPersonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public void setAttPersonNumber(NUMPERSONACLIENTEType value) {
        this.attPersonNumber = value;
    }

    /**
     * Gets the value of the attBeforeLastLogonDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttBeforeLastLogonDate() {
        return attBeforeLastLogonDate;
    }

    /**
     * Sets the value of the attBeforeLastLogonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttBeforeLastLogonDate(XMLGregorianCalendar value) {
        this.attBeforeLastLogonDate = value;
    }

    /**
     * Gets the value of the attSignMethods property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBVerTypesType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBVerTypesType getAttSignMethods() {
        return attSignMethods;
    }

    /**
     * Sets the value of the attSignMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBVerTypesType }
     *     
     */
    public void setAttSignMethods(ComIsbAlFacsegSecurityCbCBVerTypesType value) {
        this.attSignMethods = value;
    }

    /**
     * Gets the value of the attPersonalID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID getAttPersonalID() {
        return attPersonalID;
    }

    /**
     * Sets the value of the attPersonalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID }
     *     
     */
    public void setAttPersonalID(ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID value) {
        this.attPersonalID = value;
    }

    /**
     * Gets the value of the attName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttName() {
        return attName;
    }

    /**
     * Sets the value of the attName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttName(String value) {
        this.attName = value;
    }

    /**
     * Gets the value of the attDocument property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMPERSONACORPORATIVOType }
     *     
     */
    public DOCUMPERSONACORPORATIVOType getAttDocument() {
        return attDocument;
    }

    /**
     * Sets the value of the attDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMPERSONACORPORATIVOType }
     *     
     */
    public void setAttDocument(DOCUMPERSONACORPORATIVOType value) {
        this.attDocument = value;
    }

    /**
     * Gets the value of the attDocumentRep property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMPERSONACORPORATIVOType }
     *     
     */
    public DOCUMPERSONACORPORATIVOType getAttDocumentRep() {
        return attDocumentRep;
    }

    /**
     * Sets the value of the attDocumentRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMPERSONACORPORATIVOType }
     *     
     */
    public void setAttDocumentRep(DOCUMPERSONACORPORATIVOType value) {
        this.attDocumentRep = value;
    }

    /**
     * Gets the value of the attLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link IDIOMACORPORATIVOType }
     *     
     */
    public IDIOMACORPORATIVOType getAttLanguage() {
        return attLanguage;
    }

    /**
     * Sets the value of the attLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDIOMACORPORATIVOType }
     *     
     */
    public void setAttLanguage(IDIOMACORPORATIVOType value) {
        this.attLanguage = value;
    }

    /**
     * Gets the value of the attLastUnsuccessLogon property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttLastUnsuccessLogon() {
        return attLastUnsuccessLogon;
    }

    /**
     * Sets the value of the attLastUnsuccessLogon property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttLastUnsuccessLogon(XMLGregorianCalendar value) {
        this.attLastUnsuccessLogon = value;
    }

    /**
     * Gets the value of the attSecondSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttSecondSign() {
        return attSecondSign;
    }

    /**
     * Sets the value of the attSecondSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttSecondSign(String value) {
        this.attSecondSign = value;
    }

    /**
     * Gets the value of the attLastSignDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttLastSignDate() {
        return attLastSignDate;
    }

    /**
     * Sets the value of the attLastSignDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttLastSignDate(XMLGregorianCalendar value) {
        this.attLastSignDate = value;
    }

    /**
     * Gets the value of the attLogonImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttLogonImage() {
        return attLogonImage;
    }

    /**
     * Sets the value of the attLogonImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttLogonImage(String value) {
        this.attLogonImage = value;
    }

    /**
     * Gets the value of the attLogonPhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttLogonPhrase() {
        return attLogonPhrase;
    }

    /**
     * Sets the value of the attLogonPhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttLogonPhrase(String value) {
        this.attLogonPhrase = value;
    }

    /**
     * Gets the value of the attmTANRevokedSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttmTANRevokedSign() {
        return attmTANRevokedSign;
    }

    /**
     * Sets the value of the attmTANRevokedSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttmTANRevokedSign(String value) {
        this.attmTANRevokedSign = value;
    }

    /**
     * Gets the value of the attCompanyID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID getAttCompanyID() {
        return attCompanyID;
    }

    /**
     * Sets the value of the attCompanyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID }
     *     
     */
    public void setAttCompanyID(ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID value) {
        this.attCompanyID = value;
    }

    /**
     * Gets the value of the attCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttCompanyName() {
        return attCompanyName;
    }

    /**
     * Sets the value of the attCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttCompanyName(String value) {
        this.attCompanyName = value;
    }

    /**
     * Gets the value of the attLegalPersonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public NUMPERSONACLIENTEType getAttLegalPersonNumber() {
        return attLegalPersonNumber;
    }

    /**
     * Sets the value of the attLegalPersonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public void setAttLegalPersonNumber(NUMPERSONACLIENTEType value) {
        this.attLegalPersonNumber = value;
    }

    /**
     * Gets the value of the attStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttStartDate() {
        return attStartDate;
    }

    /**
     * Sets the value of the attStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttStartDate(XMLGregorianCalendar value) {
        this.attStartDate = value;
    }

    /**
     * Gets the value of the attEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttEndDate() {
        return attEndDate;
    }

    /**
     * Sets the value of the attEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttEndDate(XMLGregorianCalendar value) {
        this.attEndDate = value;
    }

    /**
     * Gets the value of the attLockUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttLockUser() {
        return attLockUser;
    }

    /**
     * Sets the value of the attLockUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttLockUser(String value) {
        this.attLockUser = value;
    }

    /**
     * Gets the value of the attAuthenticationLastError property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttAuthenticationLastError() {
        return attAuthenticationLastError;
    }

    /**
     * Sets the value of the attAuthenticationLastError property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttAuthenticationLastError(String value) {
        this.attAuthenticationLastError = value;
    }

    /**
     * Gets the value of the attSignByPositionsActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttSignByPositionsActive() {
        return attSignByPositionsActive;
    }

    /**
     * Sets the value of the attSignByPositionsActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttSignByPositionsActive(String value) {
        this.attSignByPositionsActive = value;
    }

    /**
     * Gets the value of the attRevocationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttRevocationDate() {
        return attRevocationDate;
    }

    /**
     * Sets the value of the attRevocationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttRevocationDate(XMLGregorianCalendar value) {
        this.attRevocationDate = value;
    }

    /**
     * Gets the value of the attLockDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAttLockDate() {
        return attLockDate;
    }

    /**
     * Sets the value of the attLockDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAttLockDate(XMLGregorianCalendar value) {
        this.attLockDate = value;
    }

    /**
     * Gets the value of the attPasswordActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttPasswordActive() {
        return attPasswordActive;
    }

    /**
     * Sets the value of the attPasswordActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttPasswordActive(String value) {
        this.attPasswordActive = value;
    }

    /**
     * Gets the value of the attOTPPushID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID getAttOTPPushID() {
        return attOTPPushID;
    }

    /**
     * Sets the value of the attOTPPushID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID }
     *     
     */
    public void setAttOTPPushID(ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID value) {
        this.attOTPPushID = value;
    }

    /**
     * Gets the value of the attOTPPushRevokedSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttOTPPushRevokedSign() {
        return attOTPPushRevokedSign;
    }

    /**
     * Sets the value of the attOTPPushRevokedSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttOTPPushRevokedSign(String value) {
        this.attOTPPushRevokedSign = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attCompanyID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attCompanyID"
    })
    public static class AttCompanyID {

        @XmlElement(nillable = true)
        protected List<String> attCompanyID;

        /**
         * Gets the value of the attCompanyID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attCompanyID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttCompanyID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttCompanyID() {
            if (attCompanyID == null) {
                attCompanyID = new ArrayList<String>();
            }
            return this.attCompanyID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attContractNumber" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attContractNumber"
    })
    public static class AttContractNumber {

        @XmlElement(nillable = true)
        protected List<String> attContractNumber;

        /**
         * Gets the value of the attContractNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attContractNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttContractNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttContractNumber() {
            if (attContractNumber == null) {
                attContractNumber = new ArrayList<String>();
            }
            return this.attContractNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attCreditCardNumber" type="{http://www.isban.es/webservices/TDCs}PAN_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attCreditCardNumber"
    })
    public static class AttCreditCardNumber {

        @XmlElement(nillable = true)
        protected List<String> attCreditCardNumber;

        /**
         * Gets the value of the attCreditCardNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attCreditCardNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttCreditCardNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttCreditCardNumber() {
            if (attCreditCardNumber == null) {
                attCreditCardNumber = new ArrayList<String>();
            }
            return this.attCreditCardNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attMobile" type="{http://www.isban.es/webservices/TDCs}TELEFONO_INTERNACIONAL_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attMobile"
    })
    public static class AttMobile {

        @XmlElement(nillable = true)
        protected List<String> attMobile;

        /**
         * Gets the value of the attMobile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attMobile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttMobile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttMobile() {
            if (attMobile == null) {
                attMobile = new ArrayList<String>();
            }
            return this.attMobile;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attOTPPushID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_LARGA_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attOTPPushID"
    })
    public static class AttOTPPushID {

        @XmlElement(nillable = true)
        protected List<String> attOTPPushID;

        /**
         * Gets the value of the attOTPPushID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attOTPPushID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttOTPPushID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttOTPPushID() {
            if (attOTPPushID == null) {
                attOTPPushID = new ArrayList<String>();
            }
            return this.attOTPPushID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attPersonalID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attPersonalID"
    })
    public static class AttPersonalID {

        @XmlElement(nillable = true)
        protected List<String> attPersonalID;

        /**
         * Gets the value of the attPersonalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attPersonalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttPersonalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttPersonalID() {
            if (attPersonalID == null) {
                attPersonalID = new ArrayList<String>();
            }
            return this.attPersonalID;
        }

    }

}
