//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.ObtRepresentantes_E_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.ObtRepresentantes_E_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="representado" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" minOccurs="0"/>
 *         &lt;element name="empresa" type="{http://www.isban.es/webservices/TDCs}EMPRESA_Type" minOccurs="0"/>
 *         &lt;element name="canal" type="{http://www.isban.es/webservices/TDCs}CODIGO_DE_CANAL_Type" minOccurs="0"/>
 *         &lt;element name="memento" type="{http://www.isban.es/webservices/TDCs}SQLMEMENTO_Type" minOccurs="0"/>
 *         &lt;element name="indRepo" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.ObtRepresentantes_E_Type", propOrder = {
    "representado",
    "empresa",
    "canal",
    "memento",
    "indRepo"
})
public class ComIsbSanoguServiciosdirogEFCbObtRepresentantesEType {

    protected NUMPERSONACLIENTEType representado;
    protected String empresa;
    protected String canal;
    protected String memento;
    protected String indRepo;

    /**
     * Gets the value of the representado property.
     * 
     * @return
     *     possible object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public NUMPERSONACLIENTEType getRepresentado() {
        return representado;
    }

    /**
     * Sets the value of the representado property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public void setRepresentado(NUMPERSONACLIENTEType value) {
        this.representado = value;
    }

    /**
     * Gets the value of the empresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpresa() {
        return empresa;
    }

    /**
     * Sets the value of the empresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpresa(String value) {
        this.empresa = value;
    }

    /**
     * Gets the value of the canal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanal() {
        return canal;
    }

    /**
     * Sets the value of the canal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanal(String value) {
        this.canal = value;
    }

    /**
     * Gets the value of the memento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemento() {
        return memento;
    }

    /**
     * Sets the value of the memento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemento(String value) {
        this.memento = value;
    }

    /**
     * Gets the value of the indRepo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndRepo() {
        return indRepo;
    }

    /**
     * Sets the value of the indRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndRepo(String value) {
        this.indRepo = value;
    }

}
