//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.EvalCondTraspTotPP_S_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.EvalCondTraspTotPP_S_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indicadorOK" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="indOperPend" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.EvalCondTraspTotPP_S_Type", propOrder = {
    "indicadorOK",
    "indOperPend"
})
public class ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPSType {

    protected String indicadorOK;
    protected String indOperPend;

    /**
     * Gets the value of the indicadorOK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorOK() {
        return indicadorOK;
    }

    /**
     * Sets the value of the indicadorOK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorOK(String value) {
        this.indicadorOK = value;
    }

    /**
     * Gets the value of the indOperPend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndOperPend() {
        return indOperPend;
    }

    /**
     * Sets the value of the indOperPend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndOperPend(String value) {
        this.indOperPend = value;
    }

}
