//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.Interviniente_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.Interviniente_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cliente" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" minOccurs="0"/>
 *         &lt;element name="tipIntervencion" type="{http://www.isban.es/webservices/TDCs}TIPO_DE_INTERVENCION_Type" minOccurs="0"/>
 *         &lt;element name="formaIntervencion" type="{http://www.isban.es/webservices/TDCs}FORMA_DE_INTERVENCION_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.Interviniente_Type", propOrder = {
    "cliente",
    "tipIntervencion",
    "formaIntervencion"
})
public class ComIsbSanoguServiciosdirogEFCbIntervinienteType {

    protected NUMPERSONACLIENTEType cliente;
    protected String tipIntervencion;
    protected String formaIntervencion;

    /**
     * Gets the value of the cliente property.
     * 
     * @return
     *     possible object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public NUMPERSONACLIENTEType getCliente() {
        return cliente;
    }

    /**
     * Sets the value of the cliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public void setCliente(NUMPERSONACLIENTEType value) {
        this.cliente = value;
    }

    /**
     * Gets the value of the tipIntervencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipIntervencion() {
        return tipIntervencion;
    }

    /**
     * Sets the value of the tipIntervencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipIntervencion(String value) {
        this.tipIntervencion = value;
    }

    /**
     * Gets the value of the formaIntervencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaIntervencion() {
        return formaIntervencion;
    }

    /**
     * Sets the value of the formaIntervencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaIntervencion(String value) {
        this.formaIntervencion = value;
    }

}
