//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.Pag_E_recContPlaPe_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.Pag_E_recContPlaPe_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indRepos" type="{http://www.isban.es/webservices/TDCs}INDICADOR_GENERICO_Type" minOccurs="0"/>
 *         &lt;element name="contratoRepo" type="{http://www.isban.es/webservices/TDCc}CONTRATO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.Pag_E_recContPlaPe_Type", propOrder = {
    "indRepos",
    "contratoRepo"
})
public class ComIsbSanoguServiciosdirogEFCbPagERecContPlaPeType {

    protected String indRepos;
    protected CONTRATOType contratoRepo;

    /**
     * Gets the value of the indRepos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndRepos() {
        return indRepos;
    }

    /**
     * Sets the value of the indRepos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndRepos(String value) {
        this.indRepos = value;
    }

    /**
     * Gets the value of the contratoRepo property.
     * 
     * @return
     *     possible object is
     *     {@link CONTRATOType }
     *     
     */
    public CONTRATOType getContratoRepo() {
        return contratoRepo;
    }

    /**
     * Sets the value of the contratoRepo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTRATOType }
     *     
     */
    public void setContratoRepo(CONTRATOType value) {
        this.contratoRepo = value;
    }

}
