//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.CalcCondTraspFI_S_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.CalcCondTraspFI_S_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="importeCalc" type="{http://www.isban.es/webservices/TDCc}IMPORTE_Type" minOccurs="0"/>
 *         &lt;element name="participacionesCalc" type="{http://www.isban.es/webservices/TDCs}PARTICIPACIONES_RETENIDAS_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.CalcCondTraspFI_S_Type", propOrder = {
    "importeCalc",
    "participacionesCalc"
})
public class ComIsbSanoguServiciosdirogEFCbCalcCondTraspFISType {

    protected IMPORTEType importeCalc;
    protected BigDecimal participacionesCalc;

    /**
     * Gets the value of the importeCalc property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORTEType }
     *     
     */
    public IMPORTEType getImporteCalc() {
        return importeCalc;
    }

    /**
     * Sets the value of the importeCalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORTEType }
     *     
     */
    public void setImporteCalc(IMPORTEType value) {
        this.importeCalc = value;
    }

    /**
     * Gets the value of the participacionesCalc property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParticipacionesCalc() {
        return participacionesCalc;
    }

    /**
     * Sets the value of the participacionesCalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParticipacionesCalc(BigDecimal value) {
        this.participacionesCalc = value;
    }

}
