//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.CalCondTraspFI_E_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.CalCondTraspFI_E_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoTraspaso" type="{http://www.isban.es/webservices/TDCs}INDICADOR_GENERICO_Type" minOccurs="0"/>
 *         &lt;element name="saldoDispo" type="{http://www.isban.es/webservices/TDCs}PARTICIPACIONES_RETENIDAS_Type" minOccurs="0"/>
 *         &lt;element name="valorLiquid" type="{http://www.isban.es/webservices/TDCc}VALOR_LIQUIDATIVO_FI_Type" minOccurs="0"/>
 *         &lt;element name="importeFondo" type="{http://www.isban.es/webservices/TDCc}IMPORTE_Type" minOccurs="0"/>
 *         &lt;element name="participacionesTrasp" type="{http://www.isban.es/webservices/TDCs}PARTICIPACIONES_RETENIDAS_Type" minOccurs="0"/>
 *         &lt;element name="importeTrasp" type="{http://www.isban.es/webservices/TDCc}IMPORTE_Type" minOccurs="0"/>
 *         &lt;element name="contrato" type="{http://www.isban.es/webservices/TDCc}CONTRATO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.CalCondTraspFI_E_Type", propOrder = {
    "tipoTraspaso",
    "saldoDispo",
    "valorLiquid",
    "importeFondo",
    "participacionesTrasp",
    "importeTrasp",
    "contrato"
})
public class ComIsbSanoguServiciosdirogEFCbCalCondTraspFIEType {

    protected String tipoTraspaso;
    protected BigDecimal saldoDispo;
    protected VALORLIQUIDATIVOFIType valorLiquid;
    protected IMPORTEType importeFondo;
    protected BigDecimal participacionesTrasp;
    protected IMPORTEType importeTrasp;
    protected CONTRATOType contrato;

    /**
     * Gets the value of the tipoTraspaso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoTraspaso() {
        return tipoTraspaso;
    }

    /**
     * Sets the value of the tipoTraspaso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoTraspaso(String value) {
        this.tipoTraspaso = value;
    }

    /**
     * Gets the value of the saldoDispo property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSaldoDispo() {
        return saldoDispo;
    }

    /**
     * Sets the value of the saldoDispo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSaldoDispo(BigDecimal value) {
        this.saldoDispo = value;
    }

    /**
     * Gets the value of the valorLiquid property.
     * 
     * @return
     *     possible object is
     *     {@link VALORLIQUIDATIVOFIType }
     *     
     */
    public VALORLIQUIDATIVOFIType getValorLiquid() {
        return valorLiquid;
    }

    /**
     * Sets the value of the valorLiquid property.
     * 
     * @param value
     *     allowed object is
     *     {@link VALORLIQUIDATIVOFIType }
     *     
     */
    public void setValorLiquid(VALORLIQUIDATIVOFIType value) {
        this.valorLiquid = value;
    }

    /**
     * Gets the value of the importeFondo property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORTEType }
     *     
     */
    public IMPORTEType getImporteFondo() {
        return importeFondo;
    }

    /**
     * Sets the value of the importeFondo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORTEType }
     *     
     */
    public void setImporteFondo(IMPORTEType value) {
        this.importeFondo = value;
    }

    /**
     * Gets the value of the participacionesTrasp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParticipacionesTrasp() {
        return participacionesTrasp;
    }

    /**
     * Sets the value of the participacionesTrasp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParticipacionesTrasp(BigDecimal value) {
        this.participacionesTrasp = value;
    }

    /**
     * Gets the value of the importeTrasp property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORTEType }
     *     
     */
    public IMPORTEType getImporteTrasp() {
        return importeTrasp;
    }

    /**
     * Sets the value of the importeTrasp property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORTEType }
     *     
     */
    public void setImporteTrasp(IMPORTEType value) {
        this.importeTrasp = value;
    }

    /**
     * Gets the value of the contrato property.
     * 
     * @return
     *     possible object is
     *     {@link CONTRATOType }
     *     
     */
    public CONTRATOType getContrato() {
        return contrato;
    }

    /**
     * Sets the value of the contrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTRATOType }
     *     
     */
    public void setContrato(CONTRATOType value) {
        this.contrato = value;
    }

}
