//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosPP_S_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosPP_S_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="indFinLista" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="listaFondo" type="{http://www.isban.es/webservices/SANOGU/Serviciosdirog_e/F_sanogu_serviciosdirog_e/cbTypes/vDraft}com.isb.sanogu.serviciosdirog.e.f.cb.ListaFondoPP_Type" minOccurs="0"/>
 *         &lt;element name="repos" type="{http://www.isban.es/webservices/SANOGU/Serviciosdirog_e/F_sanogu_serviciosdirog_e/cbTypes/vDraft}com.isb.sanogu.serviciosdirog.e.f.cb.Pag_E_GeFonPlanEx_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosPP_S_Type", propOrder = {
    "indFinLista",
    "listaFondo",
    "repos"
})
public class ComIsbSanoguServiciosdirogEFCbBuscFondosPPSType {

    protected String indFinLista;
    protected ComIsbSanoguServiciosdirogEFCbListaFondoPPType listaFondo;
    protected ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType repos;

    /**
     * Gets the value of the indFinLista property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndFinLista() {
        return indFinLista;
    }

    /**
     * Sets the value of the indFinLista property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndFinLista(String value) {
        this.indFinLista = value;
    }

    /**
     * Gets the value of the listaFondo property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbSanoguServiciosdirogEFCbListaFondoPPType }
     *     
     */
    public ComIsbSanoguServiciosdirogEFCbListaFondoPPType getListaFondo() {
        return listaFondo;
    }

    /**
     * Sets the value of the listaFondo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbSanoguServiciosdirogEFCbListaFondoPPType }
     *     
     */
    public void setListaFondo(ComIsbSanoguServiciosdirogEFCbListaFondoPPType value) {
        this.listaFondo = value;
    }

    /**
     * Gets the value of the repos property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType }
     *     
     */
    public ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType getRepos() {
        return repos;
    }

    /**
     * Sets the value of the repos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType }
     *     
     */
    public void setRepos(ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType value) {
        this.repos = value;
    }

}
