//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.Cuenta_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.Cuenta_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IBAN" type="{http://www.isban.es/webservices/TDCs}CUENTA_GENERAL_Type" minOccurs="0"/>
 *         &lt;element name="descTipoInter" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_EXTRALARGA_Type" minOccurs="0"/>
 *         &lt;element name="descFormaDispo" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_EXTRALARGA_Type" minOccurs="0"/>
 *         &lt;element name="saldo" type="{http://www.isban.es/webservices/TDCc}IMPORTE_Type" minOccurs="0"/>
 *         &lt;element name="fechaSaldo" type="{http://www.isban.es/webservices/TDCs}FECHA_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="contratoPartenon" type="{http://www.isban.es/webservices/TDCc}CONTRATO_Type" minOccurs="0"/>
 *         &lt;element name="tipoIntervencion" type="{http://www.isban.es/webservices/TDCs}TIPO_DE_INTERVENCION_Type" minOccurs="0"/>
 *         &lt;element name="formaIntervencion" type="{http://www.isban.es/webservices/TDCs}FORMA_DE_INTERVENCION_Type" minOccurs="0"/>
 *         &lt;element name="subTipo" type="{http://www.isban.es/webservices/TDCc}SUBTIPO_DE_PRODUCTO_Type" minOccurs="0"/>
 *         &lt;element name="descProducto" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.Cuenta_Type", propOrder = {
    "iban",
    "descTipoInter",
    "descFormaDispo",
    "saldo",
    "fechaSaldo",
    "contratoPartenon",
    "tipoIntervencion",
    "formaIntervencion",
    "subTipo",
    "descProducto"
})
public class ComIsbSanoguServiciosdirogEFCbCuentaType {

    @XmlElement(name = "IBAN")
    protected String iban;
    protected String descTipoInter;
    protected String descFormaDispo;
    protected IMPORTEType saldo;
    protected XMLGregorianCalendar fechaSaldo;
    protected CONTRATOType contratoPartenon;
    protected String tipoIntervencion;
    protected String formaIntervencion;
    protected SUBTIPODEPRODUCTOType subTipo;
    protected String descProducto;

    /**
     * Gets the value of the iban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIBAN() {
        return iban;
    }

    /**
     * Sets the value of the iban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIBAN(String value) {
        this.iban = value;
    }

    /**
     * Gets the value of the descTipoInter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescTipoInter() {
        return descTipoInter;
    }

    /**
     * Sets the value of the descTipoInter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescTipoInter(String value) {
        this.descTipoInter = value;
    }

    /**
     * Gets the value of the descFormaDispo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescFormaDispo() {
        return descFormaDispo;
    }

    /**
     * Sets the value of the descFormaDispo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescFormaDispo(String value) {
        this.descFormaDispo = value;
    }

    /**
     * Gets the value of the saldo property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORTEType }
     *     
     */
    public IMPORTEType getSaldo() {
        return saldo;
    }

    /**
     * Sets the value of the saldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORTEType }
     *     
     */
    public void setSaldo(IMPORTEType value) {
        this.saldo = value;
    }

    /**
     * Gets the value of the fechaSaldo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaSaldo() {
        return fechaSaldo;
    }

    /**
     * Sets the value of the fechaSaldo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaSaldo(XMLGregorianCalendar value) {
        this.fechaSaldo = value;
    }

    /**
     * Gets the value of the contratoPartenon property.
     * 
     * @return
     *     possible object is
     *     {@link CONTRATOType }
     *     
     */
    public CONTRATOType getContratoPartenon() {
        return contratoPartenon;
    }

    /**
     * Sets the value of the contratoPartenon property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTRATOType }
     *     
     */
    public void setContratoPartenon(CONTRATOType value) {
        this.contratoPartenon = value;
    }

    /**
     * Gets the value of the tipoIntervencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoIntervencion() {
        return tipoIntervencion;
    }

    /**
     * Sets the value of the tipoIntervencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoIntervencion(String value) {
        this.tipoIntervencion = value;
    }

    /**
     * Gets the value of the formaIntervencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaIntervencion() {
        return formaIntervencion;
    }

    /**
     * Sets the value of the formaIntervencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaIntervencion(String value) {
        this.formaIntervencion = value;
    }

    /**
     * Gets the value of the subTipo property.
     * 
     * @return
     *     possible object is
     *     {@link SUBTIPODEPRODUCTOType }
     *     
     */
    public SUBTIPODEPRODUCTOType getSubTipo() {
        return subTipo;
    }

    /**
     * Sets the value of the subTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUBTIPODEPRODUCTOType }
     *     
     */
    public void setSubTipo(SUBTIPODEPRODUCTOType value) {
        this.subTipo = value;
    }

    /**
     * Gets the value of the descProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescProducto() {
        return descProducto;
    }

    /**
     * Sets the value of the descProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescProducto(String value) {
        this.descProducto = value;
    }

}
