//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.PlanTitular_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.PlanTitular_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contrato" type="{http://www.isban.es/webservices/TDCc}CONTRATO_Type" minOccurs="0"/>
 *         &lt;element name="ultValLiq" type="{http://www.isban.es/webservices/TDCc}VALOR_LIQUIDATIVO_PP_Type" minOccurs="0"/>
 *         &lt;element name="fecValLiq" type="{http://www.isban.es/webservices/TDCs}FECHA_GENERICA_Type" minOccurs="0"/>
 *         &lt;element name="numPartPart" type="{http://www.isban.es/webservices/TDCs}PARTICIPACIONES_RETENIDAS_Type" minOccurs="0"/>
 *         &lt;element name="impPartPart" type="{http://www.isban.es/webservices/TDCc}IMPORTE_Type" minOccurs="0"/>
 *         &lt;element name="numPartBen" type="{http://www.isban.es/webservices/TDCs}PARTICIPACIONES_RETENIDAS_Type" minOccurs="0"/>
 *         &lt;element name="impPartBen" type="{http://www.isban.es/webservices/TDCc}IMPORTE_Type" minOccurs="0"/>
 *         &lt;element name="tipoPlan" type="{http://www.isban.es/webservices/TDCs}TIPO_PLAN_GESTORA_Type" minOccurs="0"/>
 *         &lt;element name="descProducto" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" minOccurs="0"/>
 *         &lt;element name="subtipo" type="{http://www.isban.es/webservices/TDCc}SUBTIPO_DE_PRODUCTO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.PlanTitular_Type", propOrder = {
    "contrato",
    "ultValLiq",
    "fecValLiq",
    "numPartPart",
    "impPartPart",
    "numPartBen",
    "impPartBen",
    "tipoPlan",
    "descProducto",
    "subtipo"
})
public class ComIsbSanoguServiciosdirogEFCbPlanTitularType {

    protected CONTRATOType contrato;
    protected VALORLIQUIDATIVOPPType ultValLiq;
    protected XMLGregorianCalendar fecValLiq;
    protected BigDecimal numPartPart;
    protected IMPORTEType impPartPart;
    protected BigDecimal numPartBen;
    protected IMPORTEType impPartBen;
    protected String tipoPlan;
    protected String descProducto;
    protected SUBTIPODEPRODUCTOType subtipo;

    /**
     * Gets the value of the contrato property.
     * 
     * @return
     *     possible object is
     *     {@link CONTRATOType }
     *     
     */
    public CONTRATOType getContrato() {
        return contrato;
    }

    /**
     * Sets the value of the contrato property.
     * 
     * @param value
     *     allowed object is
     *     {@link CONTRATOType }
     *     
     */
    public void setContrato(CONTRATOType value) {
        this.contrato = value;
    }

    /**
     * Gets the value of the ultValLiq property.
     * 
     * @return
     *     possible object is
     *     {@link VALORLIQUIDATIVOPPType }
     *     
     */
    public VALORLIQUIDATIVOPPType getUltValLiq() {
        return ultValLiq;
    }

    /**
     * Sets the value of the ultValLiq property.
     * 
     * @param value
     *     allowed object is
     *     {@link VALORLIQUIDATIVOPPType }
     *     
     */
    public void setUltValLiq(VALORLIQUIDATIVOPPType value) {
        this.ultValLiq = value;
    }

    /**
     * Gets the value of the fecValLiq property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecValLiq() {
        return fecValLiq;
    }

    /**
     * Sets the value of the fecValLiq property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecValLiq(XMLGregorianCalendar value) {
        this.fecValLiq = value;
    }

    /**
     * Gets the value of the numPartPart property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumPartPart() {
        return numPartPart;
    }

    /**
     * Sets the value of the numPartPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumPartPart(BigDecimal value) {
        this.numPartPart = value;
    }

    /**
     * Gets the value of the impPartPart property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORTEType }
     *     
     */
    public IMPORTEType getImpPartPart() {
        return impPartPart;
    }

    /**
     * Sets the value of the impPartPart property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORTEType }
     *     
     */
    public void setImpPartPart(IMPORTEType value) {
        this.impPartPart = value;
    }

    /**
     * Gets the value of the numPartBen property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNumPartBen() {
        return numPartBen;
    }

    /**
     * Sets the value of the numPartBen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNumPartBen(BigDecimal value) {
        this.numPartBen = value;
    }

    /**
     * Gets the value of the impPartBen property.
     * 
     * @return
     *     possible object is
     *     {@link IMPORTEType }
     *     
     */
    public IMPORTEType getImpPartBen() {
        return impPartBen;
    }

    /**
     * Sets the value of the impPartBen property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMPORTEType }
     *     
     */
    public void setImpPartBen(IMPORTEType value) {
        this.impPartBen = value;
    }

    /**
     * Gets the value of the tipoPlan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPlan() {
        return tipoPlan;
    }

    /**
     * Sets the value of the tipoPlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPlan(String value) {
        this.tipoPlan = value;
    }

    /**
     * Gets the value of the descProducto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescProducto() {
        return descProducto;
    }

    /**
     * Sets the value of the descProducto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescProducto(String value) {
        this.descProducto = value;
    }

    /**
     * Gets the value of the subtipo property.
     * 
     * @return
     *     possible object is
     *     {@link SUBTIPODEPRODUCTOType }
     *     
     */
    public SUBTIPODEPRODUCTOType getSubtipo() {
        return subtipo;
    }

    /**
     * Sets the value of the subtipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUBTIPODEPRODUCTOType }
     *     
     */
    public void setSubtipo(SUBTIPODEPRODUCTOType value) {
        this.subtipo = value;
    }

}
