//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.Pag_S_buscFonFI_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.Pag_S_buscFonFI_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codISINrepos" type="{http://www.isban.es/webservices/TDCs}CODIGO_ISIN_Type" minOccurs="0"/>
 *         &lt;element name="finLista" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.Pag_S_buscFonFI_Type", propOrder = {
    "codISINrepos",
    "finLista"
})
public class ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType {

    protected String codISINrepos;
    protected String finLista;

    /**
     * Gets the value of the codISINrepos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodISINrepos() {
        return codISINrepos;
    }

    /**
     * Sets the value of the codISINrepos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodISINrepos(String value) {
        this.codISINrepos = value;
    }

    /**
     * Gets the value of the finLista property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinLista() {
        return finLista;
    }

    /**
     * Sets the value of the finLista property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinLista(String value) {
        this.finLista = value;
    }

}
