//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosFI_S_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosFI_S_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="listaFondo" type="{http://www.isban.es/webservices/SANOGU/Serviciosdirog_e/F_sanogu_serviciosdirog_e/cbTypes/vDraft}com.isb.sanogu.serviciosdirog.e.f.cb.ListaFondoFI_Type" minOccurs="0"/>
 *         &lt;element name="repos" type="{http://www.isban.es/webservices/SANOGU/Serviciosdirog_e/F_sanogu_serviciosdirog_e/cbTypes/vDraft}com.isb.sanogu.serviciosdirog.e.f.cb.Pag_S_buscFonFI_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosFI_S_Type", propOrder = {
    "listaFondo",
    "repos"
})
public class ComIsbSanoguServiciosdirogEFCbBuscFondosFISType {

    protected ComIsbSanoguServiciosdirogEFCbListaFondoFIType listaFondo;
    protected ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType repos;

    /**
     * Gets the value of the listaFondo property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbSanoguServiciosdirogEFCbListaFondoFIType }
     *     
     */
    public ComIsbSanoguServiciosdirogEFCbListaFondoFIType getListaFondo() {
        return listaFondo;
    }

    /**
     * Sets the value of the listaFondo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbSanoguServiciosdirogEFCbListaFondoFIType }
     *     
     */
    public void setListaFondo(ComIsbSanoguServiciosdirogEFCbListaFondoFIType value) {
        this.listaFondo = value;
    }

    /**
     * Gets the value of the repos property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType }
     *     
     */
    public ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType getRepos() {
        return repos;
    }

    /**
     * Sets the value of the repos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType }
     *     
     */
    public void setRepos(ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType value) {
        this.repos = value;
    }

}
