//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosFI_E_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosFI_E_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idGestora" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" minOccurs="0"/>
 *         &lt;element name="nombreFon" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" minOccurs="0"/>
 *         &lt;element name="codISIN" type="{http://www.isban.es/webservices/TDCs}CODIGO_ISIN_Type" minOccurs="0"/>
 *         &lt;element name="tipoBusqueda" type="{http://www.isban.es/webservices/TDCs}INDICADOR_GENERICO_Type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.sanogu.serviciosdirog.e.f.cb.BuscFondosFI_E_Type", propOrder = {
    "idGestora",
    "nombreFon",
    "codISIN",
    "tipoBusqueda"
})
public class ComIsbSanoguServiciosdirogEFCbBuscFondosFIEType {

    protected NUMPERSONACLIENTEType idGestora;
    protected String nombreFon;
    protected String codISIN;
    protected String tipoBusqueda;

    /**
     * Gets the value of the idGestora property.
     * 
     * @return
     *     possible object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public NUMPERSONACLIENTEType getIdGestora() {
        return idGestora;
    }

    /**
     * Sets the value of the idGestora property.
     * 
     * @param value
     *     allowed object is
     *     {@link NUMPERSONACLIENTEType }
     *     
     */
    public void setIdGestora(NUMPERSONACLIENTEType value) {
        this.idGestora = value;
    }

    /**
     * Gets the value of the nombreFon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreFon() {
        return nombreFon;
    }

    /**
     * Sets the value of the nombreFon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreFon(String value) {
        this.nombreFon = value;
    }

    /**
     * Gets the value of the codISIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodISIN() {
        return codISIN;
    }

    /**
     * Sets the value of the codISIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodISIN(String value) {
        this.codISIN = value;
    }

    /**
     * Gets the value of the tipoBusqueda property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoBusqueda() {
        return tipoBusqueda;
    }

    /**
     * Sets the value of the tipoBusqueda property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoBusqueda(String value) {
        this.tipoBusqueda = value;
    }

}
