//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.31 at 09:55:15 AM CEST 
//


package com.isb.og.wsdl.ofegui;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.isb.og.wsdl.ofegui package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.isb.og.wsdl.ofegui
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProcessInfo }
     * 
     */
    public ProcessInfo createProcessInfo() {
        return new ProcessInfo();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbRecContraFondosEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbRecContraFondosEType createComIsbSanoguServiciosdirogEFCbRecContraFondosEType() {
        return new ComIsbSanoguServiciosdirogEFCbRecContraFondosEType();
    }

    /**
     * Create an instance of {@link Faultcode }
     * 
     */
    public Faultcode createFaultcode() {
        return new Faultcode();
    }

    /**
     * Create an instance of {@link NUMPERSONACLIENTEType }
     * 
     */
    public NUMPERSONACLIENTEType createNUMPERSONACLIENTEType() {
        return new NUMPERSONACLIENTEType();
    }

    /**
     * Create an instance of {@link BuscFondosPP }
     * 
     */
    public BuscFondosPP createBuscFondosPP() {
        return new BuscFondosPP();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFExcTraspsoNoPermitido }
     * 
     */
    public ComIsbSanoguServiciosdirogEFExcTraspsoNoPermitido createComIsbSanoguServiciosdirogEFExcTraspsoNoPermitido() {
        return new ComIsbSanoguServiciosdirogEFExcTraspsoNoPermitido();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPEType createComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPEType() {
        return new ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbCuentaType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbCuentaType createComIsbSanoguServiciosdirogEFCbCuentaType() {
        return new ComIsbSanoguServiciosdirogEFCbCuentaType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscFondosFIEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscFondosFIEType createComIsbSanoguServiciosdirogEFCbBuscFondosFIEType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscFondosFIEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscFondosPPSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscFondosPPSType createComIsbSanoguServiciosdirogEFCbBuscFondosPPSType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscFondosPPSType();
    }

    /**
     * Create an instance of {@link ObtRepresentantesResponse }
     * 
     */
    public ObtRepresentantesResponse createObtRepresentantesResponse() {
        return new ObtRepresentantesResponse();
    }

    /**
     * Create an instance of {@link BuscFondosFI }
     * 
     */
    public BuscFondosFI createBuscFondosFI() {
        return new BuscFondosFI();
    }

    /**
     * Create an instance of {@link EvalCondTraspTotPPResponse }
     * 
     */
    public EvalCondTraspTotPPResponse createEvalCondTraspTotPPResponse() {
        return new EvalCondTraspTotPPResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaContratoFondoType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaContratoFondoType createComIsbSanoguServiciosdirogEFCbListaContratoFondoType() {
        return new ComIsbSanoguServiciosdirogEFCbListaContratoFondoType();
    }

    /**
     * Create an instance of {@link SUBTIPODEPRODUCTOType }
     * 
     */
    public SUBTIPODEPRODUCTOType createSUBTIPODEPRODUCTOType() {
        return new SUBTIPODEPRODUCTOType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbGestoraPPType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbGestoraPPType createComIsbSanoguServiciosdirogEFCbGestoraPPType() {
        return new ComIsbSanoguServiciosdirogEFCbGestoraPPType();
    }

    /**
     * Create an instance of {@link Subcode }
     * 
     */
    public Subcode createSubcode() {
        return new Subcode();
    }

    /**
     * Create an instance of {@link EvalCondTrasParcPPResponse }
     * 
     */
    public EvalCondTrasParcPPResponse createEvalCondTrasParcPPResponse() {
        return new EvalCondTrasParcPPResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaFondoPPType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaFondoPPType createComIsbSanoguServiciosdirogEFCbListaFondoPPType() {
        return new ComIsbSanoguServiciosdirogEFCbListaFondoPPType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaGestoraFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaGestoraFIType createComIsbSanoguServiciosdirogEFCbListaGestoraFIType() {
        return new ComIsbSanoguServiciosdirogEFCbListaGestoraFIType();
    }

    /**
     * Create an instance of {@link TechnicalException }
     * 
     */
    public TechnicalException createTechnicalException() {
        return new TechnicalException();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbSeguridadOGType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbSeguridadOGType createComIsbSanoguServiciosdirogEFCbSeguridadOGType() {
        return new ComIsbSanoguServiciosdirogEFCbSeguridadOGType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbCalCondTraspFIEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbCalCondTraspFIEType createComIsbSanoguServiciosdirogEFCbCalCondTraspFIEType() {
        return new ComIsbSanoguServiciosdirogEFCbCalCondTraspFIEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbRepresentanteType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbRepresentanteType createComIsbSanoguServiciosdirogEFCbRepresentanteType() {
        return new ComIsbSanoguServiciosdirogEFCbRepresentanteType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaGestoraPPType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaGestoraPPType createComIsbSanoguServiciosdirogEFCbListaGestoraPPType() {
        return new ComIsbSanoguServiciosdirogEFCbListaGestoraPPType();
    }

    /**
     * Create an instance of {@link RecContraFondos }
     * 
     */
    public RecContraFondos createRecContraFondos() {
        return new RecContraFondos();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscPlanFonExtPPEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscPlanFonExtPPEType createComIsbSanoguServiciosdirogEFCbBuscPlanFonExtPPEType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscPlanFonExtPPEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscFondosFISType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscFondosFISType createComIsbSanoguServiciosdirogEFCbBuscFondosFISType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscFondosFISType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFExcNoHayDatosServiciosDirOGE }
     * 
     */
    public ComIsbSanoguServiciosdirogEFExcNoHayDatosServiciosDirOGE createComIsbSanoguServiciosdirogEFExcNoHayDatosServiciosDirOGE() {
        return new ComIsbSanoguServiciosdirogEFExcNoHayDatosServiciosDirOGE();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFExcGeneralServiciosDirOGE }
     * 
     */
    public ComIsbSanoguServiciosdirogEFExcGeneralServiciosDirOGE createComIsbSanoguServiciosdirogEFExcGeneralServiciosDirOGE() {
        return new ComIsbSanoguServiciosdirogEFExcGeneralServiciosDirOGE();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagSTrasFondosType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagSTrasFondosType createComIsbSanoguServiciosdirogEFCbPagSTrasFondosType() {
        return new ComIsbSanoguServiciosdirogEFCbPagSTrasFondosType();
    }

    /**
     * Create an instance of {@link BuscGestoraPPResponse }
     * 
     */
    public BuscGestoraPPResponse createBuscGestoraPPResponse() {
        return new BuscGestoraPPResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbRecContraPlanPenEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbRecContraPlanPenEType createComIsbSanoguServiciosdirogEFCbRecContraPlanPenEType() {
        return new ComIsbSanoguServiciosdirogEFCbRecContraPlanPenEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagEBusGestFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagEBusGestFIType createComIsbSanoguServiciosdirogEFCbPagEBusGestFIType() {
        return new ComIsbSanoguServiciosdirogEFCbPagEBusGestFIType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPSType createComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPSType() {
        return new ComIsbSanoguServiciosdirogEFCbEvalCondTraspTotPPSType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscGestoraFISType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscGestoraFISType createComIsbSanoguServiciosdirogEFCbBuscGestoraFISType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscGestoraFISType();
    }

    /**
     * Create an instance of {@link CENTRODECONTRATOType }
     * 
     */
    public CENTRODECONTRATOType createCENTRODECONTRATOType() {
        return new CENTRODECONTRATOType();
    }

    /**
     * Create an instance of {@link RecContraPlaPen }
     * 
     */
    public RecContraPlaPen createRecContraPlaPen() {
        return new RecContraPlaPen();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaPlanTitularType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaPlanTitularType createComIsbSanoguServiciosdirogEFCbListaPlanTitularType() {
        return new ComIsbSanoguServiciosdirogEFCbListaPlanTitularType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaRepresentanteType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaRepresentanteType createComIsbSanoguServiciosdirogEFCbListaRepresentanteType() {
        return new ComIsbSanoguServiciosdirogEFCbListaRepresentanteType();
    }

    /**
     * Create an instance of {@link BuscGestoraPP }
     * 
     */
    public BuscGestoraPP createBuscGestoraPP() {
        return new BuscGestoraPP();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbObtenerCuentasSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbObtenerCuentasSType createComIsbSanoguServiciosdirogEFCbObtenerCuentasSType() {
        return new ComIsbSanoguServiciosdirogEFCbObtenerCuentasSType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbFondoPPType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbFondoPPType createComIsbSanoguServiciosdirogEFCbFondoPPType() {
        return new ComIsbSanoguServiciosdirogEFCbFondoPPType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagSRecContrPlaPenType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagSRecContrPlaPenType createComIsbSanoguServiciosdirogEFCbPagSRecContrPlaPenType() {
        return new ComIsbSanoguServiciosdirogEFCbPagSRecContrPlaPenType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbRecContraPlanPenSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbRecContraPlanPenSType createComIsbSanoguServiciosdirogEFCbRecContraPlanPenSType() {
        return new ComIsbSanoguServiciosdirogEFCbRecContraPlanPenSType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscPlanExtPPSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscPlanExtPPSType createComIsbSanoguServiciosdirogEFCbBuscPlanExtPPSType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscPlanExtPPSType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType createComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType() {
        return new ComIsbSanoguServiciosdirogEFCbPagEGeFonPlanExType();
    }

    /**
     * Create an instance of {@link ObtenerCuentas }
     * 
     */
    public ObtenerCuentas createObtenerCuentas() {
        return new ObtenerCuentas();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaPlanExtPPType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaPlanExtPPType createComIsbSanoguServiciosdirogEFCbListaPlanExtPPType() {
        return new ComIsbSanoguServiciosdirogEFCbListaPlanExtPPType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagERecContPlaPeType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagERecContPlaPeType createComIsbSanoguServiciosdirogEFCbPagERecContPlaPeType() {
        return new ComIsbSanoguServiciosdirogEFCbPagERecContPlaPeType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType createComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType() {
        return new ComIsbSanoguServiciosdirogEFCbPagSBuscFonFIType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbRecContrFondosSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbRecContrFondosSType createComIsbSanoguServiciosdirogEFCbRecContrFondosSType() {
        return new ComIsbSanoguServiciosdirogEFCbRecContrFondosSType();
    }

    /**
     * Create an instance of {@link Faultreason }
     * 
     */
    public Faultreason createFaultreason() {
        return new Faultreason();
    }

    /**
     * Create an instance of {@link RecContraFondosResponse }
     * 
     */
    public RecContraFondosResponse createRecContraFondosResponse() {
        return new RecContraFondosResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPlanTitularType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPlanTitularType createComIsbSanoguServiciosdirogEFCbPlanTitularType() {
        return new ComIsbSanoguServiciosdirogEFCbPlanTitularType();
    }

    /**
     * Create an instance of {@link ObtenerCuentasResponse }
     * 
     */
    public ObtenerCuentasResponse createObtenerCuentasResponse() {
        return new ObtenerCuentasResponse();
    }

    /**
     * Create an instance of {@link BuscGestoraFI }
     * 
     */
    public BuscGestoraFI createBuscGestoraFI() {
        return new BuscGestoraFI();
    }

    /**
     * Create an instance of {@link RecContraPlaPenResponse }
     * 
     */
    public RecContraPlaPenResponse createRecContraPlaPenResponse() {
        return new RecContraPlaPenResponse();
    }

    /**
     * Create an instance of {@link BuscPlanExtPPResponse }
     * 
     */
    public BuscPlanExtPPResponse createBuscPlanExtPPResponse() {
        return new BuscPlanExtPPResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaIntervinientesType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaIntervinientesType createComIsbSanoguServiciosdirogEFCbListaIntervinientesType() {
        return new ComIsbSanoguServiciosdirogEFCbListaIntervinientesType();
    }

    /**
     * Create an instance of {@link CONTRATOType }
     * 
     */
    public CONTRATOType createCONTRATOType() {
        return new CONTRATOType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaCuentasType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaCuentasType createComIsbSanoguServiciosdirogEFCbListaCuentasType() {
        return new ComIsbSanoguServiciosdirogEFCbListaCuentasType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagETrasFondosType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagETrasFondosType createComIsbSanoguServiciosdirogEFCbPagETrasFondosType() {
        return new ComIsbSanoguServiciosdirogEFCbPagETrasFondosType();
    }

    /**
     * Create an instance of {@link CENTROType }
     * 
     */
    public CENTROType createCENTROType() {
        return new CENTROType();
    }

    /**
     * Create an instance of {@link ObtRepresentantes }
     * 
     */
    public ObtRepresentantes createObtRepresentantes() {
        return new ObtRepresentantes();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbCalcCondTraspFISType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbCalcCondTraspFISType createComIsbSanoguServiciosdirogEFCbCalcCondTraspFISType() {
        return new ComIsbSanoguServiciosdirogEFCbCalcCondTraspFISType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbObtenerCuentasEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbObtenerCuentasEType createComIsbSanoguServiciosdirogEFCbObtenerCuentasEType() {
        return new ComIsbSanoguServiciosdirogEFCbObtenerCuentasEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagSBuscGestFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagSBuscGestFIType createComIsbSanoguServiciosdirogEFCbPagSBuscGestFIType() {
        return new ComIsbSanoguServiciosdirogEFCbPagSBuscGestFIType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPlanExtPPType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPlanExtPPType createComIsbSanoguServiciosdirogEFCbPlanExtPPType() {
        return new ComIsbSanoguServiciosdirogEFCbPlanExtPPType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbGestoraFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbGestoraFIType createComIsbSanoguServiciosdirogEFCbGestoraFIType() {
        return new ComIsbSanoguServiciosdirogEFCbGestoraFIType();
    }

    /**
     * Create an instance of {@link BuscGestoraFIResponse }
     * 
     */
    public BuscGestoraFIResponse createBuscGestoraFIResponse() {
        return new BuscGestoraFIResponse();
    }

    /**
     * Create an instance of {@link EvalCondTraspTotPP }
     * 
     */
    public EvalCondTraspTotPP createEvalCondTraspTotPP() {
        return new EvalCondTraspTotPP();
    }

    /**
     * Create an instance of {@link VALORLIQUIDATIVOPPType }
     * 
     */
    public VALORLIQUIDATIVOPPType createVALORLIQUIDATIVOPPType() {
        return new VALORLIQUIDATIVOPPType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbEvalCondTrasParcPPSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbEvalCondTrasParcPPSType createComIsbSanoguServiciosdirogEFCbEvalCondTrasParcPPSType() {
        return new ComIsbSanoguServiciosdirogEFCbEvalCondTrasParcPPSType();
    }

    /**
     * Create an instance of {@link EvalCondTrasParcPP }
     * 
     */
    public EvalCondTrasParcPP createEvalCondTrasParcPP() {
        return new EvalCondTrasParcPP();
    }

    /**
     * Create an instance of {@link CalCondTraspFI }
     * 
     */
    public CalCondTraspFI createCalCondTraspFI() {
        return new CalCondTraspFI();
    }

    /**
     * Create an instance of {@link TIPODEPRODUCTOType }
     * 
     */
    public TIPODEPRODUCTOType createTIPODEPRODUCTOType() {
        return new TIPODEPRODUCTOType();
    }

    /**
     * Create an instance of {@link BuscPlanExtPP }
     * 
     */
    public BuscPlanExtPP createBuscPlanExtPP() {
        return new BuscPlanExtPP();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbObtRepresentantesSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbObtRepresentantesSType createComIsbSanoguServiciosdirogEFCbObtRepresentantesSType() {
        return new ComIsbSanoguServiciosdirogEFCbObtRepresentantesSType();
    }

    /**
     * Create an instance of {@link VALORLIQUIDATIVOFIType }
     * 
     */
    public VALORLIQUIDATIVOFIType createVALORLIQUIDATIVOFIType() {
        return new VALORLIQUIDATIVOFIType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbListaFondoFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbListaFondoFIType createComIsbSanoguServiciosdirogEFCbListaFondoFIType() {
        return new ComIsbSanoguServiciosdirogEFCbListaFondoFIType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbObtRepresentantesEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbObtRepresentantesEType createComIsbSanoguServiciosdirogEFCbObtRepresentantesEType() {
        return new ComIsbSanoguServiciosdirogEFCbObtRepresentantesEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbEvalCondTrasParciPPEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbEvalCondTrasParciPPEType createComIsbSanoguServiciosdirogEFCbEvalCondTrasParciPPEType() {
        return new ComIsbSanoguServiciosdirogEFCbEvalCondTrasParciPPEType();
    }

    /**
     * Create an instance of {@link BuscFondosPPResponse }
     * 
     */
    public BuscFondosPPResponse createBuscFondosPPResponse() {
        return new BuscFondosPPResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscGestoraFIEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscGestoraFIEType createComIsbSanoguServiciosdirogEFCbBuscGestoraFIEType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscGestoraFIEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscGestoraPPSType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscGestoraPPSType createComIsbSanoguServiciosdirogEFCbBuscGestoraPPSType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscGestoraPPSType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbPagEBusFonFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbPagEBusFonFIType createComIsbSanoguServiciosdirogEFCbPagEBusFonFIType() {
        return new ComIsbSanoguServiciosdirogEFCbPagEBusFonFIType();
    }

    /**
     * Create an instance of {@link CalCondTraspFIResponse }
     * 
     */
    public CalCondTraspFIResponse createCalCondTraspFIResponse() {
        return new CalCondTraspFIResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbBuscGestoraPPEType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbBuscGestoraPPEType createComIsbSanoguServiciosdirogEFCbBuscGestoraPPEType() {
        return new ComIsbSanoguServiciosdirogEFCbBuscGestoraPPEType();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbIntervinienteType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbIntervinienteType createComIsbSanoguServiciosdirogEFCbIntervinienteType() {
        return new ComIsbSanoguServiciosdirogEFCbIntervinienteType();
    }

    /**
     * Create an instance of {@link IMPORTEType }
     * 
     */
    public IMPORTEType createIMPORTEType() {
        return new IMPORTEType();
    }

    /**
     * Create an instance of {@link BuscFondosFIResponse }
     * 
     */
    public BuscFondosFIResponse createBuscFondosFIResponse() {
        return new BuscFondosFIResponse();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbFondoFIType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbFondoFIType createComIsbSanoguServiciosdirogEFCbFondoFIType() {
        return new ComIsbSanoguServiciosdirogEFCbFondoFIType();
    }

    /**
     * Create an instance of {@link Faultreasons }
     * 
     */
    public Faultreasons createFaultreasons() {
        return new Faultreasons();
    }

    /**
     * Create an instance of {@link ComIsbSanoguServiciosdirogEFCbContratoFondoType }
     * 
     */
    public ComIsbSanoguServiciosdirogEFCbContratoFondoType createComIsbSanoguServiciosdirogEFCbContratoFondoType() {
        return new ComIsbSanoguServiciosdirogEFCbContratoFondoType();
    }

}
