//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 10:30:19 AM CEST 
//


package com.isb.wphg.security.wsdl.facseg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for com.isb.al.facseg.security.cb.CB_Search_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="com.isb.al.facseg.security.cb.CB_Search_Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attEntity" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attEntity" type="{http://www.isban.es/webservices/TDCs}EMPRESA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attEnvironment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attEnvironment" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attAlias" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attAlias" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attUID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attUID" type="{http://www.isban.es/webservices/TDCs}UID_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attName" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attName" type="{http://www.isban.es/webservices/TDCs}NOMBRE_DE_PERSONA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attSurname" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attSurname" type="{http://www.isban.es/webservices/TDCs}APELLIDO_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attFullName" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dato" type="{http://www.isban.es/webservices/TDCs}NOMBRE_DE_PERSONA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attPersonalID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attPersonalID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attPersonNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attPersonNumber" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attDocument" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attDocument" type="{http://www.isban.es/webservices/TDCc}DOCUM_PERSONA_CORPORATIVO_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attDocumentRep" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attDocumentRep" type="{http://www.isban.es/webservices/TDCc}DOCUM_PERSONA_CORPORATIVO_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attContractNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attContractNumber" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attCreditCardNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attCreditCardNumber" type="{http://www.isban.es/webservices/TDCs}PAN_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attLanguage" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attLanguage" type="{http://www.isban.es/webservices/TDCc}IDIOMA_CORPORATIVO_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attMobile" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attMobile" type="{http://www.isban.es/webservices/TDCs}TELEFONO_INTERNACIONAL_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attCompanyID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attCompanyID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attCompanyName" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attCompanyName" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_MEDIA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attLegalPersonNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attLegalPersonNumber" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attFirstTime" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attFirstTimeSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attSecondSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attLockUser" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attRevokedPassword" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attmTANRevokedSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attRevokedSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attExpirationDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Fechas_Type" minOccurs="0"/>
 *         &lt;element name="attStartDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Fechas_Type" minOccurs="0"/>
 *         &lt;element name="attEndDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Fechas_Type" minOccurs="0"/>
 *         &lt;element name="attLastLogonDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attBeforeLastLogonDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attLastUnsuccessLogon" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attLastChangePWDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attLastSignDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attSignMethods" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_VerTypes_Type" minOccurs="0"/>
 *         &lt;element name="attSignByPositionsActive" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attRevocationDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attLockDate" type="{http://www.isban.es/webservices/TECHNICAL_FACADES/Security/F_facseg_security/cbTypes/v1}com.isb.al.facseg.security.cb.CB_Search_Timestamps_Type" minOccurs="0"/>
 *         &lt;element name="attPasswordActive" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attOTPPushRevokedSign" type="{http://www.isban.es/webservices/TDCs}INDICADOR_SI-NO_Type" minOccurs="0"/>
 *         &lt;element name="attOTPPushID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="attOTPPushID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_LARGA_Type" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "com.isb.al.facseg.security.cb.CB_Search_Type", propOrder = {
    "attEntity",
    "attEnvironment",
    "attAlias",
    "attUID",
    "attName",
    "attSurname",
    "attFullName",
    "attPersonalID",
    "attPersonNumber",
    "attDocument",
    "attDocumentRep",
    "attContractNumber",
    "attCreditCardNumber",
    "attLanguage",
    "attMobile",
    "attCompanyID",
    "attCompanyName",
    "attLegalPersonNumber",
    "attFirstTime",
    "attFirstTimeSign",
    "attSecondSign",
    "attLockUser",
    "attRevokedPassword",
    "attmTANRevokedSign",
    "attRevokedSign",
    "attExpirationDate",
    "attStartDate",
    "attEndDate",
    "attLastLogonDate",
    "attBeforeLastLogonDate",
    "attLastUnsuccessLogon",
    "attLastChangePWDate",
    "attLastSignDate",
    "attSignMethods",
    "attSignByPositionsActive",
    "attRevocationDate",
    "attLockDate",
    "attPasswordActive",
    "attOTPPushRevokedSign",
    "attOTPPushID"
})
public class ComIsbAlFacsegSecurityCbCBSearchType {

    protected ComIsbAlFacsegSecurityCbCBSearchType.AttEntity attEntity;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment attEnvironment;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttAlias attAlias;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttUID attUID;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttName attName;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttSurname attSurname;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttFullName attFullName;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID attPersonalID;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber attPersonNumber;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttDocument attDocument;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep attDocumentRep;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber attContractNumber;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber attCreditCardNumber;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage attLanguage;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttMobile attMobile;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID attCompanyID;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName attCompanyName;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber attLegalPersonNumber;
    protected String attFirstTime;
    protected String attFirstTimeSign;
    protected String attSecondSign;
    protected String attLockUser;
    protected String attRevokedPassword;
    protected String attmTANRevokedSign;
    protected String attRevokedSign;
    protected ComIsbAlFacsegSecurityCbCBSearchFechasType attExpirationDate;
    protected ComIsbAlFacsegSecurityCbCBSearchFechasType attStartDate;
    protected ComIsbAlFacsegSecurityCbCBSearchFechasType attEndDate;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attLastLogonDate;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attBeforeLastLogonDate;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attLastUnsuccessLogon;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attLastChangePWDate;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attLastSignDate;
    protected ComIsbAlFacsegSecurityCbCBVerTypesType attSignMethods;
    protected String attSignByPositionsActive;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attRevocationDate;
    protected ComIsbAlFacsegSecurityCbCBSearchTimestampsType attLockDate;
    protected String attPasswordActive;
    protected String attOTPPushRevokedSign;
    protected ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID attOTPPushID;

    /**
     * Gets the value of the attEntity property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttEntity }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttEntity getAttEntity() {
        return attEntity;
    }

    /**
     * Sets the value of the attEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttEntity }
     *     
     */
    public void setAttEntity(ComIsbAlFacsegSecurityCbCBSearchType.AttEntity value) {
        this.attEntity = value;
    }

    /**
     * Gets the value of the attEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment getAttEnvironment() {
        return attEnvironment;
    }

    /**
     * Sets the value of the attEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment }
     *     
     */
    public void setAttEnvironment(ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment value) {
        this.attEnvironment = value;
    }

    /**
     * Gets the value of the attAlias property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttAlias }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttAlias getAttAlias() {
        return attAlias;
    }

    /**
     * Sets the value of the attAlias property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttAlias }
     *     
     */
    public void setAttAlias(ComIsbAlFacsegSecurityCbCBSearchType.AttAlias value) {
        this.attAlias = value;
    }

    /**
     * Gets the value of the attUID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttUID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttUID getAttUID() {
        return attUID;
    }

    /**
     * Sets the value of the attUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttUID }
     *     
     */
    public void setAttUID(ComIsbAlFacsegSecurityCbCBSearchType.AttUID value) {
        this.attUID = value;
    }

    /**
     * Gets the value of the attName property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttName }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttName getAttName() {
        return attName;
    }

    /**
     * Sets the value of the attName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttName }
     *     
     */
    public void setAttName(ComIsbAlFacsegSecurityCbCBSearchType.AttName value) {
        this.attName = value;
    }

    /**
     * Gets the value of the attSurname property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttSurname }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttSurname getAttSurname() {
        return attSurname;
    }

    /**
     * Sets the value of the attSurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttSurname }
     *     
     */
    public void setAttSurname(ComIsbAlFacsegSecurityCbCBSearchType.AttSurname value) {
        this.attSurname = value;
    }

    /**
     * Gets the value of the attFullName property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttFullName }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttFullName getAttFullName() {
        return attFullName;
    }

    /**
     * Sets the value of the attFullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttFullName }
     *     
     */
    public void setAttFullName(ComIsbAlFacsegSecurityCbCBSearchType.AttFullName value) {
        this.attFullName = value;
    }

    /**
     * Gets the value of the attPersonalID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID getAttPersonalID() {
        return attPersonalID;
    }

    /**
     * Sets the value of the attPersonalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID }
     *     
     */
    public void setAttPersonalID(ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID value) {
        this.attPersonalID = value;
    }

    /**
     * Gets the value of the attPersonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber getAttPersonNumber() {
        return attPersonNumber;
    }

    /**
     * Sets the value of the attPersonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber }
     *     
     */
    public void setAttPersonNumber(ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber value) {
        this.attPersonNumber = value;
    }

    /**
     * Gets the value of the attDocument property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttDocument }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttDocument getAttDocument() {
        return attDocument;
    }

    /**
     * Sets the value of the attDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttDocument }
     *     
     */
    public void setAttDocument(ComIsbAlFacsegSecurityCbCBSearchType.AttDocument value) {
        this.attDocument = value;
    }

    /**
     * Gets the value of the attDocumentRep property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep getAttDocumentRep() {
        return attDocumentRep;
    }

    /**
     * Sets the value of the attDocumentRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep }
     *     
     */
    public void setAttDocumentRep(ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep value) {
        this.attDocumentRep = value;
    }

    /**
     * Gets the value of the attContractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber getAttContractNumber() {
        return attContractNumber;
    }

    /**
     * Sets the value of the attContractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber }
     *     
     */
    public void setAttContractNumber(ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber value) {
        this.attContractNumber = value;
    }

    /**
     * Gets the value of the attCreditCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber getAttCreditCardNumber() {
        return attCreditCardNumber;
    }

    /**
     * Sets the value of the attCreditCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber }
     *     
     */
    public void setAttCreditCardNumber(ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber value) {
        this.attCreditCardNumber = value;
    }

    /**
     * Gets the value of the attLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage getAttLanguage() {
        return attLanguage;
    }

    /**
     * Sets the value of the attLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage }
     *     
     */
    public void setAttLanguage(ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage value) {
        this.attLanguage = value;
    }

    /**
     * Gets the value of the attMobile property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttMobile }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttMobile getAttMobile() {
        return attMobile;
    }

    /**
     * Sets the value of the attMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttMobile }
     *     
     */
    public void setAttMobile(ComIsbAlFacsegSecurityCbCBSearchType.AttMobile value) {
        this.attMobile = value;
    }

    /**
     * Gets the value of the attCompanyID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID getAttCompanyID() {
        return attCompanyID;
    }

    /**
     * Sets the value of the attCompanyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID }
     *     
     */
    public void setAttCompanyID(ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID value) {
        this.attCompanyID = value;
    }

    /**
     * Gets the value of the attCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName getAttCompanyName() {
        return attCompanyName;
    }

    /**
     * Sets the value of the attCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName }
     *     
     */
    public void setAttCompanyName(ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName value) {
        this.attCompanyName = value;
    }

    /**
     * Gets the value of the attLegalPersonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber getAttLegalPersonNumber() {
        return attLegalPersonNumber;
    }

    /**
     * Sets the value of the attLegalPersonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber }
     *     
     */
    public void setAttLegalPersonNumber(ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber value) {
        this.attLegalPersonNumber = value;
    }

    /**
     * Gets the value of the attFirstTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttFirstTime() {
        return attFirstTime;
    }

    /**
     * Sets the value of the attFirstTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttFirstTime(String value) {
        this.attFirstTime = value;
    }

    /**
     * Gets the value of the attFirstTimeSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttFirstTimeSign() {
        return attFirstTimeSign;
    }

    /**
     * Sets the value of the attFirstTimeSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttFirstTimeSign(String value) {
        this.attFirstTimeSign = value;
    }

    /**
     * Gets the value of the attSecondSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttSecondSign() {
        return attSecondSign;
    }

    /**
     * Sets the value of the attSecondSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttSecondSign(String value) {
        this.attSecondSign = value;
    }

    /**
     * Gets the value of the attLockUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttLockUser() {
        return attLockUser;
    }

    /**
     * Sets the value of the attLockUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttLockUser(String value) {
        this.attLockUser = value;
    }

    /**
     * Gets the value of the attRevokedPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttRevokedPassword() {
        return attRevokedPassword;
    }

    /**
     * Sets the value of the attRevokedPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttRevokedPassword(String value) {
        this.attRevokedPassword = value;
    }

    /**
     * Gets the value of the attmTANRevokedSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttmTANRevokedSign() {
        return attmTANRevokedSign;
    }

    /**
     * Sets the value of the attmTANRevokedSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttmTANRevokedSign(String value) {
        this.attmTANRevokedSign = value;
    }

    /**
     * Gets the value of the attRevokedSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttRevokedSign() {
        return attRevokedSign;
    }

    /**
     * Sets the value of the attRevokedSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttRevokedSign(String value) {
        this.attRevokedSign = value;
    }

    /**
     * Gets the value of the attExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchFechasType getAttExpirationDate() {
        return attExpirationDate;
    }

    /**
     * Sets the value of the attExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     *     
     */
    public void setAttExpirationDate(ComIsbAlFacsegSecurityCbCBSearchFechasType value) {
        this.attExpirationDate = value;
    }

    /**
     * Gets the value of the attStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchFechasType getAttStartDate() {
        return attStartDate;
    }

    /**
     * Sets the value of the attStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     *     
     */
    public void setAttStartDate(ComIsbAlFacsegSecurityCbCBSearchFechasType value) {
        this.attStartDate = value;
    }

    /**
     * Gets the value of the attEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchFechasType getAttEndDate() {
        return attEndDate;
    }

    /**
     * Sets the value of the attEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     *     
     */
    public void setAttEndDate(ComIsbAlFacsegSecurityCbCBSearchFechasType value) {
        this.attEndDate = value;
    }

    /**
     * Gets the value of the attLastLogonDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttLastLogonDate() {
        return attLastLogonDate;
    }

    /**
     * Sets the value of the attLastLogonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttLastLogonDate(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attLastLogonDate = value;
    }

    /**
     * Gets the value of the attBeforeLastLogonDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttBeforeLastLogonDate() {
        return attBeforeLastLogonDate;
    }

    /**
     * Sets the value of the attBeforeLastLogonDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttBeforeLastLogonDate(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attBeforeLastLogonDate = value;
    }

    /**
     * Gets the value of the attLastUnsuccessLogon property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttLastUnsuccessLogon() {
        return attLastUnsuccessLogon;
    }

    /**
     * Sets the value of the attLastUnsuccessLogon property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttLastUnsuccessLogon(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attLastUnsuccessLogon = value;
    }

    /**
     * Gets the value of the attLastChangePWDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttLastChangePWDate() {
        return attLastChangePWDate;
    }

    /**
     * Sets the value of the attLastChangePWDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttLastChangePWDate(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attLastChangePWDate = value;
    }

    /**
     * Gets the value of the attLastSignDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttLastSignDate() {
        return attLastSignDate;
    }

    /**
     * Sets the value of the attLastSignDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttLastSignDate(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attLastSignDate = value;
    }

    /**
     * Gets the value of the attSignMethods property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBVerTypesType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBVerTypesType getAttSignMethods() {
        return attSignMethods;
    }

    /**
     * Sets the value of the attSignMethods property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBVerTypesType }
     *     
     */
    public void setAttSignMethods(ComIsbAlFacsegSecurityCbCBVerTypesType value) {
        this.attSignMethods = value;
    }

    /**
     * Gets the value of the attSignByPositionsActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttSignByPositionsActive() {
        return attSignByPositionsActive;
    }

    /**
     * Sets the value of the attSignByPositionsActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttSignByPositionsActive(String value) {
        this.attSignByPositionsActive = value;
    }

    /**
     * Gets the value of the attRevocationDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttRevocationDate() {
        return attRevocationDate;
    }

    /**
     * Sets the value of the attRevocationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttRevocationDate(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attRevocationDate = value;
    }

    /**
     * Gets the value of the attLockDate property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType getAttLockDate() {
        return attLockDate;
    }

    /**
     * Sets the value of the attLockDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     *     
     */
    public void setAttLockDate(ComIsbAlFacsegSecurityCbCBSearchTimestampsType value) {
        this.attLockDate = value;
    }

    /**
     * Gets the value of the attPasswordActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttPasswordActive() {
        return attPasswordActive;
    }

    /**
     * Sets the value of the attPasswordActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttPasswordActive(String value) {
        this.attPasswordActive = value;
    }

    /**
     * Gets the value of the attOTPPushRevokedSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttOTPPushRevokedSign() {
        return attOTPPushRevokedSign;
    }

    /**
     * Sets the value of the attOTPPushRevokedSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttOTPPushRevokedSign(String value) {
        this.attOTPPushRevokedSign = value;
    }

    /**
     * Gets the value of the attOTPPushID property.
     * 
     * @return
     *     possible object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID }
     *     
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID getAttOTPPushID() {
        return attOTPPushID;
    }

    /**
     * Sets the value of the attOTPPushID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID }
     *     
     */
    public void setAttOTPPushID(ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID value) {
        this.attOTPPushID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attAlias" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attAlias"
    })
    public static class AttAlias {

        @XmlElement(nillable = true)
        protected List<String> attAlias;

        /**
         * Gets the value of the attAlias property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attAlias property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttAlias().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttAlias() {
            if (attAlias == null) {
                attAlias = new ArrayList<String>();
            }
            return this.attAlias;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attCompanyID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attCompanyID"
    })
    public static class AttCompanyID {

        @XmlElement(nillable = true)
        protected List<String> attCompanyID;

        /**
         * Gets the value of the attCompanyID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attCompanyID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttCompanyID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttCompanyID() {
            if (attCompanyID == null) {
                attCompanyID = new ArrayList<String>();
            }
            return this.attCompanyID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attCompanyName" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_MEDIA_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attCompanyName"
    })
    public static class AttCompanyName {

        @XmlElement(nillable = true)
        protected List<String> attCompanyName;

        /**
         * Gets the value of the attCompanyName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attCompanyName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttCompanyName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttCompanyName() {
            if (attCompanyName == null) {
                attCompanyName = new ArrayList<String>();
            }
            return this.attCompanyName;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attContractNumber" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attContractNumber"
    })
    public static class AttContractNumber {

        @XmlElement(nillable = true)
        protected List<String> attContractNumber;

        /**
         * Gets the value of the attContractNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attContractNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttContractNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttContractNumber() {
            if (attContractNumber == null) {
                attContractNumber = new ArrayList<String>();
            }
            return this.attContractNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attCreditCardNumber" type="{http://www.isban.es/webservices/TDCs}PAN_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attCreditCardNumber"
    })
    public static class AttCreditCardNumber {

        @XmlElement(nillable = true)
        protected List<String> attCreditCardNumber;

        /**
         * Gets the value of the attCreditCardNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attCreditCardNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttCreditCardNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttCreditCardNumber() {
            if (attCreditCardNumber == null) {
                attCreditCardNumber = new ArrayList<String>();
            }
            return this.attCreditCardNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attDocument" type="{http://www.isban.es/webservices/TDCc}DOCUM_PERSONA_CORPORATIVO_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attDocument"
    })
    public static class AttDocument {

        @XmlElement(nillable = true)
        protected List<DOCUMPERSONACORPORATIVOType> attDocument;

        /**
         * Gets the value of the attDocument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attDocument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttDocument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DOCUMPERSONACORPORATIVOType }
         * 
         * 
         */
        public List<DOCUMPERSONACORPORATIVOType> getAttDocument() {
            if (attDocument == null) {
                attDocument = new ArrayList<DOCUMPERSONACORPORATIVOType>();
            }
            return this.attDocument;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attDocumentRep" type="{http://www.isban.es/webservices/TDCc}DOCUM_PERSONA_CORPORATIVO_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attDocumentRep"
    })
    public static class AttDocumentRep {

        @XmlElement(nillable = true)
        protected List<DOCUMPERSONACORPORATIVOType> attDocumentRep;

        /**
         * Gets the value of the attDocumentRep property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attDocumentRep property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttDocumentRep().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DOCUMPERSONACORPORATIVOType }
         * 
         * 
         */
        public List<DOCUMPERSONACORPORATIVOType> getAttDocumentRep() {
            if (attDocumentRep == null) {
                attDocumentRep = new ArrayList<DOCUMPERSONACORPORATIVOType>();
            }
            return this.attDocumentRep;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attEntity" type="{http://www.isban.es/webservices/TDCs}EMPRESA_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attEntity"
    })
    public static class AttEntity {

        @XmlElement(nillable = true)
        protected List<String> attEntity;

        /**
         * Gets the value of the attEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttEntity() {
            if (attEntity == null) {
                attEntity = new ArrayList<String>();
            }
            return this.attEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attEnvironment" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attEnvironment"
    })
    public static class AttEnvironment {

        @XmlElement(nillable = true)
        protected List<String> attEnvironment;

        /**
         * Gets the value of the attEnvironment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attEnvironment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttEnvironment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttEnvironment() {
            if (attEnvironment == null) {
                attEnvironment = new ArrayList<String>();
            }
            return this.attEnvironment;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dato" type="{http://www.isban.es/webservices/TDCs}NOMBRE_DE_PERSONA_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dato"
    })
    public static class AttFullName {

        @XmlElement(nillable = true)
        protected List<String> dato;

        /**
         * Gets the value of the dato property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dato property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDato().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDato() {
            if (dato == null) {
                dato = new ArrayList<String>();
            }
            return this.dato;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attLanguage" type="{http://www.isban.es/webservices/TDCc}IDIOMA_CORPORATIVO_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attLanguage"
    })
    public static class AttLanguage {

        @XmlElement(nillable = true)
        protected List<IDIOMACORPORATIVOType> attLanguage;

        /**
         * Gets the value of the attLanguage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attLanguage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttLanguage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IDIOMACORPORATIVOType }
         * 
         * 
         */
        public List<IDIOMACORPORATIVOType> getAttLanguage() {
            if (attLanguage == null) {
                attLanguage = new ArrayList<IDIOMACORPORATIVOType>();
            }
            return this.attLanguage;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attLegalPersonNumber" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attLegalPersonNumber"
    })
    public static class AttLegalPersonNumber {

        @XmlElement(nillable = true)
        protected List<NUMPERSONACLIENTEType> attLegalPersonNumber;

        /**
         * Gets the value of the attLegalPersonNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attLegalPersonNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttLegalPersonNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NUMPERSONACLIENTEType }
         * 
         * 
         */
        public List<NUMPERSONACLIENTEType> getAttLegalPersonNumber() {
            if (attLegalPersonNumber == null) {
                attLegalPersonNumber = new ArrayList<NUMPERSONACLIENTEType>();
            }
            return this.attLegalPersonNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attMobile" type="{http://www.isban.es/webservices/TDCs}TELEFONO_INTERNACIONAL_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attMobile"
    })
    public static class AttMobile {

        @XmlElement(nillable = true)
        protected List<String> attMobile;

        /**
         * Gets the value of the attMobile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attMobile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttMobile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttMobile() {
            if (attMobile == null) {
                attMobile = new ArrayList<String>();
            }
            return this.attMobile;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attName" type="{http://www.isban.es/webservices/TDCs}NOMBRE_DE_PERSONA_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attName"
    })
    public static class AttName {

        @XmlElement(nillable = true)
        protected List<String> attName;

        /**
         * Gets the value of the attName property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attName property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttName().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttName() {
            if (attName == null) {
                attName = new ArrayList<String>();
            }
            return this.attName;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attOTPPushID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_LARGA_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attOTPPushID"
    })
    public static class AttOTPPushID {

        @XmlElement(nillable = true)
        protected List<String> attOTPPushID;

        /**
         * Gets the value of the attOTPPushID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attOTPPushID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttOTPPushID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttOTPPushID() {
            if (attOTPPushID == null) {
                attOTPPushID = new ArrayList<String>();
            }
            return this.attOTPPushID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attPersonNumber" type="{http://www.isban.es/webservices/TDCc}NUM_PERSONA_CLIENTE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attPersonNumber"
    })
    public static class AttPersonNumber {

        @XmlElement(nillable = true)
        protected List<NUMPERSONACLIENTEType> attPersonNumber;

        /**
         * Gets the value of the attPersonNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attPersonNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttPersonNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NUMPERSONACLIENTEType }
         * 
         * 
         */
        public List<NUMPERSONACLIENTEType> getAttPersonNumber() {
            if (attPersonNumber == null) {
                attPersonNumber = new ArrayList<NUMPERSONACLIENTEType>();
            }
            return this.attPersonNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attPersonalID" type="{http://www.isban.es/webservices/TDCs}DESCRIPCION_BREVE_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attPersonalID"
    })
    public static class AttPersonalID {

        @XmlElement(nillable = true)
        protected List<String> attPersonalID;

        /**
         * Gets the value of the attPersonalID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attPersonalID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttPersonalID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttPersonalID() {
            if (attPersonalID == null) {
                attPersonalID = new ArrayList<String>();
            }
            return this.attPersonalID;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attSurname" type="{http://www.isban.es/webservices/TDCs}APELLIDO_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attSurname"
    })
    public static class AttSurname {

        @XmlElement(nillable = true)
        protected List<String> attSurname;

        /**
         * Gets the value of the attSurname property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attSurname property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttSurname().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttSurname() {
            if (attSurname == null) {
                attSurname = new ArrayList<String>();
            }
            return this.attSurname;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="attUID" type="{http://www.isban.es/webservices/TDCs}UID_Type" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attUID"
    })
    public static class AttUID {

        @XmlElement(nillable = true)
        protected List<String> attUID;

        /**
         * Gets the value of the attUID property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the attUID property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAttUID().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getAttUID() {
            if (attUID == null) {
                attUID = new ArrayList<String>();
            }
            return this.attUID;
        }

    }

}
