//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 10:30:19 AM CEST 
//


package com.isb.wphg.security.wsdl.facseg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.isb.wphg.security.wsdl.facseg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.isb.wphg.security.wsdl.facseg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoExistsChallenge.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoExistsChallenge.Params createComIsbAlFacsegSecurityExcEXNoExistsChallengeParams() {
        return new ComIsbAlFacsegSecurityExcEXNoExistsChallenge.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBDataTokenValuesType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBDataTokenValuesType createComIsbAlFacsegSecurityCbCBDataTokenValuesType() {
        return new ComIsbAlFacsegSecurityCbCBDataTokenValuesType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredSType createComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredSType() {
        return new ComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUncertainSign }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUncertainSign createComIsbAlFacsegSecurityExcEXUncertainSign() {
        return new ComIsbAlFacsegSecurityExcEXUncertainSign();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcExInvalidToken.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcExInvalidToken.Params createComIsbAlFacsegSecurityExcExInvalidTokenParams() {
        return new ComIsbAlFacsegSecurityExcExInvalidToken.Params();
    }

    /**
     * Create an instance of {@link GetLoggedUserToken }
     * 
     */
    public GetLoggedUserToken createGetLoggedUserToken() {
        return new GetLoggedUserToken();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerifyResponseEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerifyResponseEType createComIsbAlFacsegSecurityCbCBVerifyResponseEType() {
        return new ComIsbAlFacsegSecurityCbCBVerifyResponseEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBOrdinalAuthDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBOrdinalAuthDataType createComIsbAlFacsegSecurityCbCBOrdinalAuthDataType() {
        return new ComIsbAlFacsegSecurityCbCBOrdinalAuthDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserListType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserListType createComIsbAlFacsegSecurityCbCBUserListType() {
        return new ComIsbAlFacsegSecurityCbCBUserListType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber createComIsbAlFacsegSecurityCbCBSearchTypeAttPersonNumber() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttPersonNumber();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRemoteRepositoriesSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRemoteRepositoriesSType createComIsbAlFacsegSecurityCbCBRemoteRepositoriesSType() {
        return new ComIsbAlFacsegSecurityCbCBRemoteRepositoriesSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerifyResponseEType.OperationData }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerifyResponseEType.OperationData createComIsbAlFacsegSecurityCbCBVerifyResponseETypeOperationData() {
        return new ComIsbAlFacsegSecurityCbCBVerifyResponseEType.OperationData();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoExistsChallenge }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoExistsChallenge createComIsbAlFacsegSecurityExcEXNoExistsChallenge() {
        return new ComIsbAlFacsegSecurityExcEXNoExistsChallenge();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDuplicatedUser.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDuplicatedUser.Params createComIsbAlFacsegSecurityExcEXDuplicatedUserParams() {
        return new ComIsbAlFacsegSecurityExcEXDuplicatedUser.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRepeatedPassword.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRepeatedPassword.Params createComIsbAlFacsegSecurityExcEXRepeatedPasswordParams() {
        return new ComIsbAlFacsegSecurityExcEXRepeatedPassword.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerTypesType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerTypesType createComIsbAlFacsegSecurityCbCBVerTypesType() {
        return new ComIsbAlFacsegSecurityCbCBVerTypesType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRepeatedPassword }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRepeatedPassword createComIsbAlFacsegSecurityExcEXRepeatedPassword() {
        return new ComIsbAlFacsegSecurityExcEXRepeatedPassword();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber createComIsbAlFacsegSecurityCbCBSearchTypeAttCreditCardNumber() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttCreditCardNumber();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesSType createComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesSType() {
        return new ComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceEType createComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceEType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUserNotActive }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUserNotActive createComIsbAlFacsegSecurityExcEXUserNotActive() {
        return new ComIsbAlFacsegSecurityExcEXUserNotActive();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoLoggedUser.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoLoggedUser.Params createComIsbAlFacsegSecurityExcEXNoLoggedUserParams() {
        return new ComIsbAlFacsegSecurityExcEXNoLoggedUser.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGenerateTokenDeviceEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGenerateTokenDeviceEType createComIsbAlFacsegSecurityCbCBGenerateTokenDeviceEType() {
        return new ComIsbAlFacsegSecurityCbCBGenerateTokenDeviceEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXFailedSign }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXFailedSign createComIsbAlFacsegSecurityExcEXFailedSign() {
        return new ComIsbAlFacsegSecurityExcEXFailedSign();
    }

    /**
     * Create an instance of {@link Subcode }
     * 
     */
    public Subcode createSubcode() {
        return new Subcode();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType.OutAux }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType.OutAux createComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSTypeOutAux() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType.OutAux();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRiskPolicyType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRiskPolicyType createComIsbAlFacsegSecurityCbCBRiskPolicyType() {
        return new ComIsbAlFacsegSecurityCbCBRiskPolicyType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType.OperationData }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType.OperationData createComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeETypeOperationData() {
        return new ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType.OperationData();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcExInvalidToken.Params0 }
     * 
     */
    public ComIsbAlFacsegSecurityExcExInvalidToken.Params0 createComIsbAlFacsegSecurityExcExInvalidTokenParams0() {
        return new ComIsbAlFacsegSecurityExcExInvalidToken.Params0();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidCredential }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidCredential createComIsbAlFacsegSecurityExcEXInvalidCredential() {
        return new ComIsbAlFacsegSecurityExcEXInvalidCredential();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesEType createComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesEType() {
        return new ComIsbAlFacsegSecurityCbCBRetrieveUserMobileDevicesEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType createComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidCredential.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidCredential.Params createComIsbAlFacsegSecurityExcEXInvalidCredentialParams() {
        return new ComIsbAlFacsegSecurityExcEXInvalidCredential.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber createComIsbAlFacsegSecurityCbCBSearchTypeAttContractNumber() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttContractNumber();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWSType createComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWSType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttAlias }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttAlias createComIsbAlFacsegSecurityCbCBSearchTypeAttAlias() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttAlias();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUncertainAuthentication }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUncertainAuthentication createComIsbAlFacsegSecurityExcEXUncertainAuthentication() {
        return new ComIsbAlFacsegSecurityExcEXUncertainAuthentication();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType createComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType() {
        return new ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeEType();
    }

    /**
     * Create an instance of {@link DESCRIPCIONTRADUCIBLEType }
     * 
     */
    public DESCRIPCIONTRADUCIBLEType createDESCRIPCIONTRADUCIBLEType() {
        return new DESCRIPCIONTRADUCIBLEType();
    }

    /**
     * Create an instance of {@link TechnicalException }
     * 
     */
    public TechnicalException createTechnicalException() {
        return new TechnicalException();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBPositionsDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBPositionsDataType createComIsbAlFacsegSecurityCbCBPositionsDataType() {
        return new ComIsbAlFacsegSecurityCbCBPositionsDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredSign.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredSign.Params createComIsbAlFacsegSecurityExcEXExpiredSignParams() {
        return new ComIsbAlFacsegSecurityExcEXExpiredSign.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGetMobileDeviceIDSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGetMobileDeviceIDSType createComIsbAlFacsegSecurityCbCBGetMobileDeviceIDSType() {
        return new ComIsbAlFacsegSecurityCbCBGetMobileDeviceIDSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXFailedAuthentication.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXFailedAuthentication.Params createComIsbAlFacsegSecurityExcEXFailedAuthenticationParams() {
        return new ComIsbAlFacsegSecurityExcEXFailedAuthentication.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNotInUseSample.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNotInUseSample.Params createComIsbAlFacsegSecurityExcEXNotInUseSampleParams() {
        return new ComIsbAlFacsegSecurityExcEXNotInUseSample.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceSType createComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceSType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByMobileDeviceSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType.UserDevice }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType.UserDevice createComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSTypeUserDevice() {
        return new ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType.UserDevice();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXTechnicalError }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXTechnicalError createComIsbAlFacsegSecurityExcEXTechnicalError() {
        return new ComIsbAlFacsegSecurityExcEXTechnicalError();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredToken.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredToken.Params createComIsbAlFacsegSecurityExcEXExpiredTokenParams() {
        return new ComIsbAlFacsegSecurityExcEXExpiredToken.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoExistsUser.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoExistsUser.Params createComIsbAlFacsegSecurityExcEXNoExistsUserParams() {
        return new ComIsbAlFacsegSecurityExcEXNoExistsUser.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXFailedSign.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXFailedSign.Params createComIsbAlFacsegSecurityExcEXFailedSignParams() {
        return new ComIsbAlFacsegSecurityExcEXFailedSign.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExceedsValidity.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExceedsValidity.Params createComIsbAlFacsegSecurityExcEXExceedsValidityParams() {
        return new ComIsbAlFacsegSecurityExcEXExceedsValidity.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchFechasType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchFechasType createComIsbAlFacsegSecurityCbCBSearchFechasType() {
        return new ComIsbAlFacsegSecurityCbCBSearchFechasType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredOTP }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredOTP createComIsbAlFacsegSecurityExcEXExpiredOTP() {
        return new ComIsbAlFacsegSecurityExcEXExpiredOTP();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXScoopSample.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXScoopSample.Params createComIsbAlFacsegSecurityExcEXScoopSampleParams() {
        return new ComIsbAlFacsegSecurityExcEXScoopSample.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSignatureChallengeSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSignatureChallengeSType createComIsbAlFacsegSecurityCbCBSignatureChallengeSType() {
        return new ComIsbAlFacsegSecurityCbCBSignatureChallengeSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBCredentialDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBCredentialDataType createComIsbAlFacsegSecurityCbCBCredentialDataType() {
        return new ComIsbAlFacsegSecurityCbCBCredentialDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidParameters.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidParameters.Params createComIsbAlFacsegSecurityExcEXInvalidParametersParams() {
        return new ComIsbAlFacsegSecurityExcEXInvalidParameters.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttMobile }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttMobile createComIsbAlFacsegSecurityCbCBSearchTypeAttMobile() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttMobile();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXLockedUser.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXLockedUser.Params createComIsbAlFacsegSecurityExcEXLockedUserParams() {
        return new ComIsbAlFacsegSecurityExcEXLockedUser.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExceedsValidity }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExceedsValidity createComIsbAlFacsegSecurityExcEXExceedsValidity() {
        return new ComIsbAlFacsegSecurityExcEXExceedsValidity();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber createComIsbAlFacsegSecurityCbCBUserTypeAttCreditCardNumber() {
        return new ComIsbAlFacsegSecurityCbCBUserType.AttCreditCardNumber();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredToken }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredToken createComIsbAlFacsegSecurityExcEXExpiredToken() {
        return new ComIsbAlFacsegSecurityExcEXExpiredToken();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNewPasswordNotEqual.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNewPasswordNotEqual.Params createComIsbAlFacsegSecurityExcEXNewPasswordNotEqualParams() {
        return new ComIsbAlFacsegSecurityExcEXNewPasswordNotEqual.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXAtributoSinRestriccion }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXAtributoSinRestriccion createComIsbAlFacsegSecurityExcEXAtributoSinRestriccion() {
        return new ComIsbAlFacsegSecurityExcEXAtributoSinRestriccion();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName createComIsbAlFacsegSecurityCbCBSearchTypeAttCompanyName() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyName();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttDocument }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttDocument createComIsbAlFacsegSecurityCbCBSearchTypeAttDocument() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttDocument();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID createComIsbAlFacsegSecurityCbCBUserTypeAttCompanyID() {
        return new ComIsbAlFacsegSecurityCbCBUserType.AttCompanyID();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBOperationDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBOperationDataType createComIsbAlFacsegSecurityCbCBOperationDataType() {
        return new ComIsbAlFacsegSecurityCbCBOperationDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage createComIsbAlFacsegSecurityCbCBSearchTypeAttLanguage() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttLanguage();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID createComIsbAlFacsegSecurityCbCBUserTypeAttOTPPushID() {
        return new ComIsbAlFacsegSecurityCbCBUserType.AttOTPPushID();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment createComIsbAlFacsegSecurityCbCBSearchTypeAttEnvironment() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttEnvironment();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidSample }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidSample createComIsbAlFacsegSecurityExcEXInvalidSample() {
        return new ComIsbAlFacsegSecurityExcEXInvalidSample();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBEnabledRiskPoliciesSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBEnabledRiskPoliciesSType createComIsbAlFacsegSecurityCbCBEnabledRiskPoliciesSType() {
        return new ComIsbAlFacsegSecurityCbCBEnabledRiskPoliciesSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep createComIsbAlFacsegSecurityCbCBSearchTypeAttDocumentRep() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttDocumentRep();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXScoopSample }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXScoopSample createComIsbAlFacsegSecurityExcEXScoopSample() {
        return new ComIsbAlFacsegSecurityExcEXScoopSample();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType createComIsbAlFacsegSecurityCbCBSearchType() {
        return new ComIsbAlFacsegSecurityCbCBSearchType();
    }

    /**
     * Create an instance of {@link Faultreason }
     * 
     */
    public Faultreason createFaultreason() {
        return new Faultreason();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredSign.Params0 }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredSign.Params0 createComIsbAlFacsegSecurityExcEXExpiredSignParams0() {
        return new ComIsbAlFacsegSecurityExcEXExpiredSign.Params0();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBDataTokenType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBDataTokenType createComIsbAlFacsegSecurityCbCBDataTokenType() {
        return new ComIsbAlFacsegSecurityCbCBDataTokenType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID createComIsbAlFacsegSecurityCbCBSearchTypeAttPersonalID() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttPersonalID();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttUID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttUID createComIsbAlFacsegSecurityCbCBSearchTypeAttUID() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttUID();
    }

    /**
     * Create an instance of {@link Faultreasons }
     * 
     */
    public Faultreasons createFaultreasons() {
        return new Faultreasons();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBExtendedAuthDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBExtendedAuthDataType createComIsbAlFacsegSecurityCbCBExtendedAuthDataType() {
        return new ComIsbAlFacsegSecurityCbCBExtendedAuthDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID createComIsbAlFacsegSecurityCbCBUserTypeAttPersonalID() {
        return new ComIsbAlFacsegSecurityCbCBUserType.AttPersonalID();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNotActivePassword.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNotActivePassword.Params createComIsbAlFacsegSecurityExcEXNotActivePasswordParams() {
        return new ComIsbAlFacsegSecurityExcEXNotActivePassword.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticationCredentialEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticationCredentialEType createComIsbAlFacsegSecurityCbCBAuthenticationCredentialEType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticationCredentialEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRevokedOTP.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRevokedOTP.Params createComIsbAlFacsegSecurityExcEXRevokedOTPParams() {
        return new ComIsbAlFacsegSecurityExcEXRevokedOTP.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSignatureChallengeEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSignatureChallengeEType createComIsbAlFacsegSecurityCbCBSignatureChallengeEType() {
        return new ComIsbAlFacsegSecurityCbCBSignatureChallengeEType();
    }

    /**
     * Create an instance of {@link NUMPERSONACLIENTEType }
     * 
     */
    public NUMPERSONACLIENTEType createNUMPERSONACLIENTEType() {
        return new NUMPERSONACLIENTEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRevokedPassword.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRevokedPassword.Params createComIsbAlFacsegSecurityExcEXRevokedPasswordParams() {
        return new ComIsbAlFacsegSecurityExcEXRevokedPassword.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoLoggedUser }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoLoggedUser createComIsbAlFacsegSecurityExcEXNoLoggedUser() {
        return new ComIsbAlFacsegSecurityExcEXNoLoggedUser();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSignaturePositionsDataSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSignaturePositionsDataSType createComIsbAlFacsegSecurityCbCBSignaturePositionsDataSType() {
        return new ComIsbAlFacsegSecurityCbCBSignaturePositionsDataSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredOTP.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredOTP.Params createComIsbAlFacsegSecurityExcEXExpiredOTPParams() {
        return new ComIsbAlFacsegSecurityExcEXExpiredOTP.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDeviceNotActive.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDeviceNotActive.Params createComIsbAlFacsegSecurityExcEXDeviceNotActiveParams() {
        return new ComIsbAlFacsegSecurityExcEXDeviceNotActive.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttName }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttName createComIsbAlFacsegSecurityCbCBSearchTypeAttName() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttName();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNotActivePassword }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNotActivePassword createComIsbAlFacsegSecurityExcEXNotActivePassword() {
        return new ComIsbAlFacsegSecurityExcEXNotActivePassword();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXSignTypeNotPermitted.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXSignTypeNotPermitted.Params createComIsbAlFacsegSecurityExcEXSignTypeNotPermittedParams() {
        return new ComIsbAlFacsegSecurityExcEXSignTypeNotPermitted.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredToken.Params0 }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredToken.Params0 createComIsbAlFacsegSecurityExcEXExpiredTokenParams0() {
        return new ComIsbAlFacsegSecurityExcEXExpiredToken.Params0();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXFirstTime }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXFirstTime createComIsbAlFacsegSecurityExcEXFirstTime() {
        return new ComIsbAlFacsegSecurityExcEXFirstTime();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttEntity }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttEntity createComIsbAlFacsegSecurityCbCBSearchTypeAttEntity() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttEntity();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcExInvalidToken }
     * 
     */
    public ComIsbAlFacsegSecurityExcExInvalidToken createComIsbAlFacsegSecurityExcExInvalidToken() {
        return new ComIsbAlFacsegSecurityExcExInvalidToken();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXFailedAuthentication }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXFailedAuthentication createComIsbAlFacsegSecurityExcEXFailedAuthentication() {
        return new ComIsbAlFacsegSecurityExcEXFailedAuthentication();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXLockedUser }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXLockedUser createComIsbAlFacsegSecurityExcEXLockedUser() {
        return new ComIsbAlFacsegSecurityExcEXLockedUser();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDeviceNotActive }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDeviceNotActive createComIsbAlFacsegSecurityExcEXDeviceNotActive() {
        return new ComIsbAlFacsegSecurityExcEXDeviceNotActive();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNotInUseSample }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNotInUseSample createComIsbAlFacsegSecurityExcEXNotInUseSample() {
        return new ComIsbAlFacsegSecurityExcEXNotInUseSample();
    }

    /**
     * Create an instance of {@link GetLoggedUserTokenResponse }
     * 
     */
    public GetLoggedUserTokenResponse createGetLoggedUserTokenResponse() {
        return new GetLoggedUserTokenResponse();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDeviceNotActive.Params0 }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDeviceNotActive.Params0 createComIsbAlFacsegSecurityExcEXDeviceNotActiveParams0() {
        return new ComIsbAlFacsegSecurityExcEXDeviceNotActive.Params0();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType createComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType.OutAux }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType.OutAux createComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSTypeOutAux() {
        return new ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType.OutAux();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredEType createComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredEType() {
        return new ComIsbAlFacsegSecurityCbCBIsMobileDeviceRegisteredEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoServiceAvailable.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoServiceAvailable.Params createComIsbAlFacsegSecurityExcEXNoServiceAvailableParams() {
        return new ComIsbAlFacsegSecurityExcEXNoServiceAvailable.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticationDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticationDataType createComIsbAlFacsegSecurityCbCBAuthenticationDataType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticationDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRevokedPassword }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRevokedPassword createComIsbAlFacsegSecurityExcEXRevokedPassword() {
        return new ComIsbAlFacsegSecurityExcEXRevokedPassword();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType createComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType() {
        return new ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoResults }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoResults createComIsbAlFacsegSecurityExcEXNoResults() {
        return new ComIsbAlFacsegSecurityExcEXNoResults();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBValidateDataTokenResultType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBValidateDataTokenResultType createComIsbAlFacsegSecurityCbCBValidateDataTokenResultType() {
        return new ComIsbAlFacsegSecurityCbCBValidateDataTokenResultType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType createComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType() {
        return new ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoExistsRepository.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoExistsRepository.Params createComIsbAlFacsegSecurityExcEXNoExistsRepositoryParams() {
        return new ComIsbAlFacsegSecurityExcEXNoExistsRepository.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthPositionsCredentialEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthPositionsCredentialEType createComIsbAlFacsegSecurityCbCBAuthPositionsCredentialEType() {
        return new ComIsbAlFacsegSecurityCbCBAuthPositionsCredentialEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeSType createComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeSType() {
        return new ComIsbAlFacsegSecurityCbCBGetAuthenticationChallengeSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUserNotRegisteredInService }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUserNotRegisteredInService createComIsbAlFacsegSecurityExcEXUserNotRegisteredInService() {
        return new ComIsbAlFacsegSecurityExcEXUserNotRegisteredInService();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRestrictoresType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRestrictoresType createComIsbAlFacsegSecurityCbCBRestrictoresType() {
        return new ComIsbAlFacsegSecurityCbCBRestrictoresType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDuplicatedSession }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDuplicatedSession createComIsbAlFacsegSecurityExcEXDuplicatedSession() {
        return new ComIsbAlFacsegSecurityExcEXDuplicatedSession();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXFirstTime.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXFirstTime.Params createComIsbAlFacsegSecurityExcEXFirstTimeParams() {
        return new ComIsbAlFacsegSecurityExcEXFirstTime.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGenerateTokenDeviceSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGenerateTokenDeviceSType createComIsbAlFacsegSecurityCbCBGenerateTokenDeviceSType() {
        return new ComIsbAlFacsegSecurityCbCBGenerateTokenDeviceSType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXAtributoSinRestriccion.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXAtributoSinRestriccion.Params createComIsbAlFacsegSecurityExcEXAtributoSinRestriccionParams() {
        return new ComIsbAlFacsegSecurityExcEXAtributoSinRestriccion.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredPassword.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredPassword.Params createComIsbAlFacsegSecurityExcEXExpiredPasswordParams() {
        return new ComIsbAlFacsegSecurityExcEXExpiredPassword.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBPoliticasType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBPoliticasType createComIsbAlFacsegSecurityCbCBPoliticasType() {
        return new ComIsbAlFacsegSecurityCbCBPoliticasType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoExistsRepository }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoExistsRepository createComIsbAlFacsegSecurityExcEXNoExistsRepository() {
        return new ComIsbAlFacsegSecurityExcEXNoExistsRepository();
    }

    /**
     * Create an instance of {@link VerifyCredential }
     * 
     */
    public VerifyCredential createVerifyCredential() {
        return new VerifyCredential();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNewPasswordNotEqual }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNewPasswordNotEqual createComIsbAlFacsegSecurityExcEXNewPasswordNotEqual() {
        return new ComIsbAlFacsegSecurityExcEXNewPasswordNotEqual();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredPassword }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredPassword createComIsbAlFacsegSecurityExcEXExpiredPassword() {
        return new ComIsbAlFacsegSecurityExcEXExpiredPassword();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttSurname }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttSurname createComIsbAlFacsegSecurityCbCBSearchTypeAttSurname() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttSurname();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRevokedOTP }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRevokedOTP createComIsbAlFacsegSecurityExcEXRevokedOTP() {
        return new ComIsbAlFacsegSecurityExcEXRevokedOTP();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRevokedSign }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRevokedSign createComIsbAlFacsegSecurityExcEXRevokedSign() {
        return new ComIsbAlFacsegSecurityExcEXRevokedSign();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber createComIsbAlFacsegSecurityCbCBSearchTypeAttLegalPersonNumber() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttLegalPersonNumber();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoResults.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoResults.Params createComIsbAlFacsegSecurityExcEXNoResultsParams() {
        return new ComIsbAlFacsegSecurityExcEXNoResults.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGetMobileDeviceIDEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGetMobileDeviceIDEType createComIsbAlFacsegSecurityCbCBGetMobileDeviceIDEType() {
        return new ComIsbAlFacsegSecurityCbCBGetMobileDeviceIDEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXRevokedSign.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXRevokedSign.Params createComIsbAlFacsegSecurityExcEXRevokedSignParams() {
        return new ComIsbAlFacsegSecurityExcEXRevokedSign.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDuplicatedUser }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDuplicatedUser createComIsbAlFacsegSecurityExcEXDuplicatedUser() {
        return new ComIsbAlFacsegSecurityExcEXDuplicatedUser();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredCredential }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredCredential createComIsbAlFacsegSecurityExcEXExpiredCredential() {
        return new ComIsbAlFacsegSecurityExcEXExpiredCredential();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBIdentificationDataType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBIdentificationDataType createComIsbAlFacsegSecurityCbCBIdentificationDataType() {
        return new ComIsbAlFacsegSecurityCbCBIdentificationDataType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation createComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation() {
        return new ComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidKey }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidKey createComIsbAlFacsegSecurityExcEXInvalidKey() {
        return new ComIsbAlFacsegSecurityExcEXInvalidKey();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoServiceAvailable }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoServiceAvailable createComIsbAlFacsegSecurityExcEXNoServiceAvailable() {
        return new ComIsbAlFacsegSecurityExcEXNoServiceAvailable();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID createComIsbAlFacsegSecurityCbCBSearchTypeAttCompanyID() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttCompanyID();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType.AttMobile }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttMobile createComIsbAlFacsegSecurityCbCBUserTypeAttMobile() {
        return new ComIsbAlFacsegSecurityCbCBUserType.AttMobile();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSignatureChallengeEType.OperationData }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSignatureChallengeEType.OperationData createComIsbAlFacsegSecurityCbCBSignatureChallengeETypeOperationData() {
        return new ComIsbAlFacsegSecurityCbCBSignatureChallengeEType.OperationData();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredCredential.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredCredential.Params createComIsbAlFacsegSecurityExcEXExpiredCredentialParams() {
        return new ComIsbAlFacsegSecurityExcEXExpiredCredential.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidSample.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidSample.Params createComIsbAlFacsegSecurityExcEXInvalidSampleParams() {
        return new ComIsbAlFacsegSecurityExcEXInvalidSample.Params();
    }

    /**
     * Create an instance of {@link DOCUMPERSONACORPORATIVOType }
     * 
     */
    public DOCUMPERSONACORPORATIVOType createDOCUMPERSONACORPORATIVOType() {
        return new DOCUMPERSONACORPORATIVOType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType.InAux }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType.InAux createComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsETypeInAux() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByBiometricsEType.InAux();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserMobileDeviceType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserMobileDeviceType createComIsbAlFacsegSecurityCbCBUserMobileDeviceType() {
        return new ComIsbAlFacsegSecurityCbCBUserMobileDeviceType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidParameters }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidParameters createComIsbAlFacsegSecurityExcEXInvalidParameters() {
        return new ComIsbAlFacsegSecurityExcEXInvalidParameters();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttFullName }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttFullName createComIsbAlFacsegSecurityCbCBSearchTypeAttFullName() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttFullName();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUncertainAuthentication.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUncertainAuthentication.Params createComIsbAlFacsegSecurityExcEXUncertainAuthenticationParams() {
        return new ComIsbAlFacsegSecurityExcEXUncertainAuthentication.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType createComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID createComIsbAlFacsegSecurityCbCBSearchTypeAttOTPPushID() {
        return new ComIsbAlFacsegSecurityCbCBSearchType.AttOTPPushID();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesEType createComIsbAlFacsegSecurityCbCBRetrieveUserDevicesEType() {
        return new ComIsbAlFacsegSecurityCbCBRetrieveUserDevicesEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXInvalidKey.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXInvalidKey.Params createComIsbAlFacsegSecurityExcEXInvalidKeyParams() {
        return new ComIsbAlFacsegSecurityExcEXInvalidKey.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType.InAux }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType.InAux createComIsbAlFacsegSecurityCbCBVerifyBIOSignatureETypeInAux() {
        return new ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType.InAux();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBSearchTimestampsType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBSearchTimestampsType createComIsbAlFacsegSecurityCbCBSearchTimestampsType() {
        return new ComIsbAlFacsegSecurityCbCBSearchTimestampsType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBRestrictorType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBRestrictorType createComIsbAlFacsegSecurityCbCBRestrictorType() {
        return new ComIsbAlFacsegSecurityCbCBRestrictorType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXTechnicalError.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXTechnicalError.Params createComIsbAlFacsegSecurityExcEXTechnicalErrorParams() {
        return new ComIsbAlFacsegSecurityExcEXTechnicalError.Params();
    }

    /**
     * Create an instance of {@link IDIOMACORPORATIVOType }
     * 
     */
    public IDIOMACORPORATIVOType createIDIOMACORPORATIVOType() {
        return new IDIOMACORPORATIVOType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXDuplicatedSession.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXDuplicatedSession.Params createComIsbAlFacsegSecurityExcEXDuplicatedSessionParams() {
        return new ComIsbAlFacsegSecurityExcEXDuplicatedSession.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber createComIsbAlFacsegSecurityCbCBUserTypeAttContractNumber() {
        return new ComIsbAlFacsegSecurityCbCBUserType.AttContractNumber();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUncertainSign.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUncertainSign.Params createComIsbAlFacsegSecurityExcEXUncertainSignParams() {
        return new ComIsbAlFacsegSecurityExcEXUncertainSign.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXExpiredSign }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXExpiredSign createComIsbAlFacsegSecurityExcEXExpiredSign() {
        return new ComIsbAlFacsegSecurityExcEXExpiredSign();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBPublicKeyType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBPublicKeyType createComIsbAlFacsegSecurityCbCBPublicKeyType() {
        return new ComIsbAlFacsegSecurityCbCBPublicKeyType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBUserType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBUserType createComIsbAlFacsegSecurityCbCBUserType() {
        return new ComIsbAlFacsegSecurityCbCBUserType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUserNotActive.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUserNotActive.Params createComIsbAlFacsegSecurityExcEXUserNotActiveParams() {
        return new ComIsbAlFacsegSecurityExcEXUserNotActive.Params();
    }

    /**
     * Create an instance of {@link VerifyCredentialResponse }
     * 
     */
    public VerifyCredentialResponse createVerifyCredentialResponse() {
        return new VerifyCredentialResponse();
    }

    /**
     * Create an instance of {@link ProcessInfo }
     * 
     */
    public ProcessInfo createProcessInfo() {
        return new ProcessInfo();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation.Params createComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperationParams() {
        return new ComIsbAlFacsegSecurityExcEXSignDoesNotMatchOperation.Params();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXSignTypeNotPermitted }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXSignTypeNotPermitted createComIsbAlFacsegSecurityExcEXSignTypeNotPermitted() {
        return new ComIsbAlFacsegSecurityExcEXSignTypeNotPermitted();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType.OperationData }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType.OperationData createComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWETypeOperationData() {
        return new ComIsbAlFacsegSecurityCbCBAuthenticateByOTPHWEType.OperationData();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType createComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType() {
        return new ComIsbAlFacsegSecurityCbCBVerifyBIOSignatureEType();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXNoExistsUser }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXNoExistsUser createComIsbAlFacsegSecurityExcEXNoExistsUser() {
        return new ComIsbAlFacsegSecurityExcEXNoExistsUser();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityCbCBGetRegisteredMobileDeviceUserSType }
     * 
     */
    public ComIsbAlFacsegSecurityCbCBGetRegisteredMobileDeviceUserSType createComIsbAlFacsegSecurityCbCBGetRegisteredMobileDeviceUserSType() {
        return new ComIsbAlFacsegSecurityCbCBGetRegisteredMobileDeviceUserSType();
    }

    /**
     * Create an instance of {@link Faultcode }
     * 
     */
    public Faultcode createFaultcode() {
        return new Faultcode();
    }

    /**
     * Create an instance of {@link ComIsbAlFacsegSecurityExcEXUserNotRegisteredInService.Params }
     * 
     */
    public ComIsbAlFacsegSecurityExcEXUserNotRegisteredInService.Params createComIsbAlFacsegSecurityExcEXUserNotRegisteredInServiceParams() {
        return new ComIsbAlFacsegSecurityExcEXUserNotRegisteredInService.Params();
    }

}
